### ISSUE TITLE
Task running every minute.

### ISSUE THREAD

**Issue by sp1rs** [celery/django-celery-beat#108]
```
@periodic_task(run_every=crontab(hour="*/2"))
def pass_x_to_y():
      # Some code.
      return

# Cdoe is running every minute. Any reason why?
```

**Comment by moseb** [comment]
For the record and whoe ever finds this ticket again:

The initializer of `crontab` reads:
```
    def __init__(self, minute='*', hour='*', day_of_week='*',
                 day_of_month='*', month_of_year='*', **kwargs):
```
Hence `hour="*/2"` should make `* */2 * * *` so it should run every minute for one hour, then pause an hour, then get back to each-minute execution.
