### ISSUE TITLE
Are crontab schedules with multiple minutes/hours/dow/wom/moy supported?

### ISSUE THREAD

**Issue by realjackofall** [celery/django-celery-beat#111]
django-celery used to allow periodic tasks with crontab schedule of format "5,10,15 1,2 * * *".
This doesn't seem to work in django-celery-beat. Is this not supported or does it not work?

More details in this SO thread - https://stackoverflow.com/questions/47468605/does-django-celery-beat-support-crontab-schedules-with-multiple-minutes-hours

**Comment by ShaheedHaque** [comment]
I just edited the SO thread with a possible answer.

**Comment by realjackofall** [comment]
Why is this closed? What is the solution? @ShaheedHaque has admitted that comma separated values DO NOT work in the SO thread.
