### ISSUE TITLE
Interval is not work when i set enabled crontab and TIME_ZONE

### ISSUE THREAD

**Issue by jonedos** [celery/django-celery-beat#112]
django setting.py:
TIME_ZONE = 'Asia/Chongqing'
CELERY_TIMEZONE = TIME_ZONE

interval: enabled,  1 seconds 
crontab: enabled,  */1 * * * *

only crontab is working

**Comment by khoanm** [comment]
I've got the same problem, wait for the solution soon.

**Comment by JoshYuJump** [comment]
Same here, waiting for `celery 4.2`

**Comment by rightx2** [comment]
In my case, interval works well but cron doesn't work...

**Comment by kliver** [comment]
I had the same problem too, I removed CELERY_TIMEZONE this had not effect to me anyways and I think caused a double timezone calculation.

**Comment by auvipy** [comment]
I think the issue is already fixed. ping if not.
