### ISSUE TITLE
Release version 1.1.1

### ISSUE THREAD

**Issue by thedrow** [celery/django-celery-beat#120]
We need to ensure that this time there's a changelog for all previous releases as well.
@auvipy Would you mind taking care of this release?

**Comment by muhtarc4n** [comment]
Do we have any ETA?

**Comment by sobolevn** [comment]
Yeap, that's breaking our release process. Since we do this check in our CI: `python manage.py makemigrations --dry-run --check`

**Comment by thedrow** [comment]
ping @auvipy

**Comment by muhtarc4n** [comment]
Guys, are we going to release bug fix?

**Comment by muhtarc4n** [comment]
@sobolevn We do dry-run in PR checks. It helps us to catch migration conflicts but right now we are blocked in django upgrade branch due to bug.

**Comment by ShaheedHaque** [comment]
I realise that getting a release out can be fraught, but it would be wonderful if #122 might be snuck in to 1.1.1. I believe it is a 1-line fix (famous last words...).

**Comment by ShaheedHaque** [comment]
So of course it was not 1-line, but PR #123 addresses issue #122.

**Comment by muhtarc4n** [comment]
Are we going to release this bug fix version?

**Comment by gregorypease280** [comment]
I am greatly anticipating the release that contains the bug fixes.

**Comment by thedrow** [comment]
1.1.1 released. Thank you for your patience.
