### ISSUE TITLE
Missing migration recreated alongside my app's migrations.

### ISSUE THREAD

**Issue by bryson** [celery/django-celery-beat#125]
I get this every time I run `makemigrations` for my Django app. 

Using v1.1.0 with Django 1.11.9

```
/usr/local/lib/python3.5/dist-packages/django_celery_beat/migrations/0005_auto_20180209_2247.py
    - Alter field event on solarschedule
```

**Comment by ShaheedHaque** [comment]
See #92. I believe this is fixed, and these issues will be closeable on next release (which I infer is imminent).
