### ISSUE TITLE
Question: Task names in django_celery_results

### ISSUE THREAD

**Issue by ACPK** [celery/django-celery-beat#130]
When viewing "django_celery_results" in Django's admin area, how can an admin:

1. See the associated task name
2. I only see two days worth of tasks. How can I keep a log of all completed and failed jobs?

**Comment by michauds** [comment]
1. I'm assuming you're talking about the `django-celery-results` project? It's already been implemeneted in master. Unfortunately, last release doesn't include it. (assuming you've installed from pip)
2. you can play with the `result_expires` configuration value (http://docs.celeryproject.org/en/latest/userguide/configuration.html#std:setting-result_expires). Setting it to `None` or `0` should allow you to keep a log of all tasks.
