### ISSUE TITLE
Timezone change warning instructions needs updating

### ISSUE THREAD

**Issue by harelw** [celery/django-celery-beat#133]
New instructions:

```
from django_celery_beat.models import PeriodicTask, PeriodicTasks
PeriodicTask.objects.all().update(last_run_at=None)
for task in PeriodicTask.objects.all():
    PeriodicTasks.changed(task)
```

https://github.com/celery/django-celery-beat/blob/60b7fc624528ac213ff2c6aa77e0063c63f727ea/docs/includes/introduction.txt#L39

**Comment by viperfx** [comment]
@harelw should the last_run_at field get populated? I still see mine show None
