### ISSUE TITLE
Keep running after the update 1.1.1

### ISSUE THREAD

**Issue by kevindwei** [celery/django-celery-beat#135]
after the update django-celery-beat==1.1.1  ,the task keeps running,?????
sysytem:centos7
celery (4.1.0)

**Comment by nikokio** [comment]
Hello,

Same here : when installing 1.1.1, the tasks are launched infinitely (hundreds times per second)

The issue is located in schedulers.py on changes around last_run_at : if I revert only these 3 or 4 lines to the old code (1.1.0) it works again.

**Comment by nikokio** [comment]
There is clearly a bug with the new last_run_at aware field.

I started celery beat on 2018-06-04 at 8:27+02:00 which immediately ran a job "*/5 8-18 * * *".
Then, with a debug line I added in the "is_due" method, I can see the following sequence:

1. The last_run_at date read in database was 2018-06-01 13:56:54.401200+02:00. is_due returned schedstate(is_due=True, next=147.780663)
=> All is normal
2. 0.1 second later, last_run_at is 2018-06-04 06:27:32.222629+00:09 and is_due returns schedstate(is_due=False, next=5007.503904)

We can see the last_run_at date has a timezone problem and the is_due then calculates a wrong next value (which is good according the LRA value...)

**Comment by jerzyk** [comment]
thousands of tasks generated by scheduler

celery:4.2.1 (windowlicker) kombu:4.2.1 py:2.7.15 billiard:3.5.0.4 redis:2.10.6

USE_TZ = False
CELERY_ENABLE_UTC = False
CELERY_TIMEZONE = TIME_ZONE  # same as main timezone

when `USE_TZ` switched to `True` - beat starts working properly

**Comment by maerteijn** [comment]
I can confirm @jerzyk comments above. This is not the case with version 1.1.0

**Comment by maerteijn** [comment]
@auvipy Could you provide us the commit where this issue was fixed? (to learn from). Or is it not fixed yet?

**Comment by auvipy** [comment]
have you tried 1.4.0 release?
