### ISSUE TITLE
PeriodicTask doesn't start tasks

### ISSUE THREAD

**Issue by kezelyx** [celery/django-celery-beat#142]
celery -A app beat -l debug -S django
celery -A app worker -l debug 

settings:
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

>>> django_celery_beat.VERSION
version_info_t(major=1, minor=1, micro=1, releaselevel='', serial='')
>>> celery.VERSION
version_info_t(major=4, minor=2, micro=0, releaselevel='rc2', serial='')

>>> from djcelery.models import PeriodicTask
>>> PeriodicTask.objects.all()
<ExtendedQuerySet [<PeriodicTask: Proxy checker Task: every 10 seconds>]>

Also IntervalSchedule.SECONDS raises an exception:
    type object 'IntervalSchedule' has no attribute 'SECONDS'
So I use a pure string for IntervalSchedule:
period='seconds'

After starting a beat. I just see the next lines and nothing more:
[2018-05-03 13:15:42,011: DEBUG/MainProcess] beat: Waking up in 5.00 seconds.
[2018-05-03 13:15:47,023: DEBUG/MainProcess] beat: Waking up in 5.00 seconds.
[2018-05-03 13:15:52,032: DEBUG/MainProcess] beat: Waking up in 5.00 seconds.
[2018-05-03 13:15:57,042: DEBUG/MainProcess] beat: Waking up in 5.00 seconds.
[2018-05-03 13:16:02,053: DEBUG/MainProcess] beat: Waking up in 5.00 seconds.

**Comment by kezelyx** [comment]
>>> import pprint;pprint.pprint({k:v for k,v in celery.conf.items() if k.startswith('beat')})
{}
>>> celery.conf.beat_schedule
{}

**Comment by kezelyx** [comment]
Even if I add a task to config:

CELERY_BEAT_SCHEDULE = {
    'task-number-one': {
        'task': 'app1.tasks.task_number_one',
        'schedule': crontab(minute=59, hour=23)
}}

I'm getting the same result - nothing.

**Comment by Iceten** [comment]
@kezelyx  Hello, I might have the same prolem you encountered ([this one](https://stackoverflow.com/questions/58676954/celery-beat-handlers-on-after-configure-finalize-are-not-working-with-add-period)). Could you please give me an advice on your solution?
 Thank you in advance!
