### ISSUE TITLE
Changing crontab of one task makes all tasks with the same old crontab execute

### ISSUE THREAD

**Issue by srolel** [celery/django-celery-beat#143]
Say I have 3 tasks with "0 1 * * *". If I pick one and change is to "10 * * * *", then at that time (say 15:10 if I changed it after 14:10), all 3 tasks will get executed, instead of just the one I changed. This is with version 1.0.1

**Comment by techman83** [comment]
Sounds like they all link to the same Crontab? Which if that's the case would be expected behaviour. You'd need to create a new Crontab and set it on the task that you want to be different if that's the case.

**Comment by Mosho1** [comment]
Yes, of course, I do create a new crontab.

**Comment by auvipy** [comment]
closing as stale for now.
