### ISSUE TITLE
Intervals get Grouped together after Adding, Updating, Removing Periodic Tasks

### ISSUE THREAD

**Issue by willwen** [celery/django-celery-beat#146]
Problem:
I have a django web app that creates Periodic Tasks in the MySQL db. After creating multiple tasks, the tasks get grouped together and all run on the same interval, instead of running on the interval they were initially created on.

every time you enabled/disabled/created/removed a periodic task, django-celery-beat restarts the interval `PeriodicTasks.update()`:
```[2018-06-07 20:33:20,642: INFO/MainProcess] DatabaseScheduler: Schedule changed.```

I tested locally, and was able to effectively push off tasks indefinitely:
Now Assume Development Env tasks have an interval of 5 min
but right before 5 minutes came up, I created a new periodic task
then the schedule resets, and the original task gets bundled up with this newly created task’s schedule

I would have expected periodic tasks to run on the same interval they were created, regardless if other tasks were created:
expected:
```
12:00 am create task A (1hr interval)
12:30 am create task B (1hr interval)
1:00am task A run
1:30 am task B run
```
actual:
```
12:00 am create task A (1hr interval)
12:30 am create task B (1hr interval)
12:30 am Schedule Changed.
1:30 am task A run
1:30 am task B run
```

My solution is to change interval schedules to CRON tab schedules.

**Comment by auvipy** [comment]
I think this is already fixed in master
