### ISSUE TITLE
Running one-off task stops all periodical tasks

### ISSUE THREAD

**Issue by putsi** [celery/django-celery-beat#150]
I'm running the development version which is installed via pip and noticed an issue related to the new one-off feature.

If there are n amount of tasks that are run periodically (e.g. once a minute) and the user runs some other task with the one-off attribute, the periodical tasks are not run anymore after the one-off task stops. 

Everything seems normal when inspected from the web interface (oneoff-task is disabled and the others are enabled) and from logs (scheduler keeps checking for tasks but doesn't simply notice/send the periodicals).
When the celery worker is restarted, the periodical tasks start running normally.

I tried to debug what is causing this but could not find any specific function.

**Comment by hartwork** [comment]
Which version of django-celery-beat is affected?

**Comment by vbabiy** [comment]
@putsi I have seen this as well. It is caused by 

```
    def is_due(self, last_run_at):
        if not self.enabled:
            return schedstate(is_due=False, next=None)
        rem_delta = self.remaining_estimate(None)
        remaining_s = max(rem_delta.total_seconds(), 0)
        if remaining_s == 0:
            if self.model:
                self.model.enabled = False
                self.model.save()
            return schedstate(is_due=True, next=None)
        return schedstate(is_due=False, next=remaining_s)
```

Not handling one of task correctly, and disabling the clocked schedule but not the one of task. Once in the this state the task is never due and blocks all other tasks during the tick.

I think #341 will fix this.

@auvipy I am seeing this on 2.0.0

**Comment by auvipy** [comment]
> @putsi I have seen this as well. It is caused by
> 
> ```
>     def is_due(self, last_run_at):
>         if not self.enabled:
>             return schedstate(is_due=False, next=None)
>         rem_delta = self.remaining_estimate(None)
>         remaining_s = max(rem_delta.total_seconds(), 0)
>         if remaining_s == 0:
>             if self.model:
>                 self.model.enabled = False
>                 self.model.save()
>             return schedstate(is_due=True, next=None)
>         return schedstate(is_due=False, next=remaining_s)
> ```
> 
> Not handling one of task correctly, and disabling the clocked schedule but not the one of task. Once in the this state the task is never due and blocks all other tasks during the tick.
> 
> I think #341 will fix this.
> 
> @auvipy I am seeing this on 2.0.0

i request you to review that PR and change that in a nonbreakable way

**Comment by yywing** [comment]
`schedstate(is_due=False, next=None)` will make it stuck.

**Comment by hartwork** [comment]
@auvipy did PR #341 fix this? Is that why you just closed the issue?

**Comment by auvipy** [comment]
that should have. but if you hit with something like this, let us know

**Comment by hartwork** [comment]
Alright, thanks for the clarification :pray:
