### ISSUE TITLE
shared task pass argument via celery beat periodic task

### ISSUE THREAD

**Issue by sandykaka** [celery/django-celery-beat#152]
I setup celery beat as

```
celery -A proj beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler 
```
And I have a method as def get_data(name) and I setup tasks.py as

```
@shared_task
def get_data(name):
    views.get_data(name)
```
And in Django admin in `periodic task` I selected `get_data` and passed Arguments: as `["test_name"]` But I get an error

`celery.beat.SchedulingError: Couldn't apply scheduled task get_data: get_data() takes 0 positional arguments but 1 was given`
I also tried Keyword arguments: but doesn't work.

If I don't pass any arguments in worker I get error

`TypeError: get_data() missing 1 required positional argument: 'name'`
How can I pass name=test_name as argument?

**Comment by Kinzowa** [comment]
Why not in the file tasks.py?
