### ISSUE TITLE
Beat scheduler crashes - InterfaceError: connection already closed

### ISSUE THREAD

**Issue by MilanPecov** [celery/django-celery-beat#159]
```
celery==4.2.1
django-celery-beat==1.1.1
postgres=postgres:9.6-alpine
```

celery beat runs good for a while but then when `Writing entries...` action comes it crashes with this error. Is there any workaround this?

![image](https://user-images.githubusercontent.com/4331824/44733560-2124e200-aae8-11e8-9926-55eea8df9734.png)

**Comment by wrvdklooster** [comment]
See issue #158 : same issue with workaround.

**Comment by norac89** [comment]
Had the same issue. The solution provided in #158 helped me finding the problem. I had to override the schedule_changed() method and remove close_old_connections() from it. 

Problems seems to come from #157.

**Comment by MilanPecov** [comment]
Thanks for the answers @wrvdklooster and @norac89 I will deploy that temporary fix
