### ISSUE TITLE
scheduler never picks up CELERY_TIMEZONE setting as 'Europe/London'

### ISSUE THREAD

**Issue by devangmehta123** [celery/django-celery-beat#161]
We are struggling to get CELERY_TIMEZONE to be recognized as 'Europe/London'. It always works as UTC even after I set it explictly in the settings file. 

All other CELERY settings are picked up correctly, including this one: CELERY_BEAT_SCHEDULER='django_celery_beat.schedulers:DatabaseScheduler'

Our Django is 1.10.2, celery is 4.2.1, django-celery-beat is 1.1.1.

I have checked our Django settings file. It has USE_TZ = True and TIME_ZONE = 'UTC'.

There is no explicit setting for CELERY_ENABLE_UTC and I believe the default is True.

When I set the crontab, it always seems to use the time set as UTC time. So, I never get the daylight savings adjustment for London in the crontab. 

For example, I set a test task to run at 8 am today, which is September 23rd at about 7:55. It did not run in 5 minutes. But if I had set it as 7 am, it would run in 5 minutes.

It just seems to be a small mistake somewhere because the documentation does mention that it should work. Can someone help?

**Comment by longfeilove7** [comment]
i have the same problem.

**Comment by auvipy** [comment]
this should have been fixed now
