### ISSUE TITLE
timezone as field doesn't work

### ISSUE THREAD

**Issue by alfredrumss** [celery/django-celery-beat#162]
When I set up 'timezone' as field trigger an exception `django.core.exceptions.FieldError: Invalid field name(s) for model CrontabSchedule: 'timezone'.`

**Comment by auvipy** [comment]
is it fixed with 1.4.0 release?

**Comment by liquidpele** [comment]
I'm not sure what this issue is for.  Can you please provide more information and steps to reproduce the problem with the latest version?
