### ISSUE TITLE
Regression on DatabaseScheduler.schedule 

### ISSUE THREAD

**Issue by pkolios** [celery/django-celery-beat#169]
Hello there, I have been facing an issue which I think is caused by this commit https://github.com/celery/django-celery-beat/commit/ab2b5be36b43eaf9b5d8f72e05d23e6a8830ba5e. The current celery scheduler implementation is testing if `self._heap is None` here https://github.com/celery/celery/blob/5cdaebf776dfab539a8b44bb961f96d81d523383/celery/beat.py#L293

With this change this, `self._heap` is never none and the call to `self.schedules_equal(self.old_schedulers, self.schedule)` is executed resulting in the following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/apps/beat.py", line 109, in start_scheduler
    service.start()
  File "/usr/local/lib/python3.7/site-packages/celery/beat.py", line 588, in start
    interval = self.scheduler.tick()
  File "/usr/local/lib/python3.7/site-packages/celery/beat.py", line 291, in tick
    not self.schedules_equal(self.old_schedulers, self.schedule)):
  File "/usr/local/lib/python3.7/site-packages/celery/beat.py", line 317, in schedules_equal
    if set(old_schedules.keys()) != set(new_schedules.keys()):
AttributeError: 'NoneType' object has no attribute 'keys'
```

Eventually causing the scheduler to exit.

**Comment by rsichny** [comment]
can you check if the issue still occurs if using code from latest master?

**Comment by feuloren** [comment]
Fixed for me on master 👍

**Comment by auvipy** [comment]
thanks all for your feedback
