### ISSUE TITLE
Can't create task if interval or solar schedule is selected

### ISSUE THREAD

**Issue by lucasdavila86** [celery/django-celery-beat#172]
I'm only able to a create scheduled task if I use a crontab schedule. I think this was introduced in this line
https://github.com/celery/django-celery-beat/compare/v1.1.1...master#diff-eeed49a50aa95de80188931bb26bee4eR328

Maybe this should be the solution
```
if self.interval and self.solar:
    raise ValidationError({
        'solar': [err_msg]
    })
```

**Comment by zuoakang** [comment]
**When I chose Interval, why do I need to remind me to set Solar?**

> env
- python 3.6
- django_celery_beat==1.2.0

![image](https://user-images.githubusercontent.com/22383362/47482000-ea5d1500-d867-11e8-8152-d4c2cf213d66.png)

**Comment by legshort** [comment]
I also did downgraded to 1.1.1 too

**Comment by auvipy** [comment]
try 1.4 release
