### ISSUE TITLE
django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')

### ISSUE THREAD

**Issue by iTraceur** [celery/django-celery-beat#18]
In migrate time getting the error, mysql charset is utf8mb4.

**Comment by mheppner** [comment]
Can you provide the full error message? It would be helpful to pinpoint which field is causing this. What version of MySQL are you using and which Python driver?

It seems like when you use `utf8mb4`, the 4-length characters cause the [max key size to be 191](https://code.djangoproject.com/ticket/18392), and some of the keys used in `django-celery-beat` are 200. You can switch to `utf8` instead for the columns or tables that are using the max of 200.

**Comment by iTraceur** [comment]
Yes, I wanted my mysql to support emoji, so I
changed the default charset of my mysql  to utf8mb4, then caused the problem. 
And I had solved it by upgrade the mysql version to 5.7, Its default row_format is "dynamic" what supports larger "max key size".

**Comment by iTraceur** [comment]
Another way as you said, set the max_length value of CharField less then 192 in the low version of mysql.

**Comment by JoshYuJump** [comment]
@iTraceur How to deal with it in `MySQL 5.6`
