### ISSUE TITLE
New release of django-celery-beat

### ISSUE THREAD

**Issue by tinylambda** [celery/django-celery-beat#187]
I found that several bugs were fixed last month, I think it's time to create a new release.

**Comment by yywing** [comment]
And I am care about how  can bump 27f73a565734a2538765723767ed1c96276566e9 -> 1.2.1.
Why fix migrations #183 in this way?

**Comment by rsichny** [comment]
There's still one issue described in (this comment)[https://github.com/celery/django-celery-beat/issues/158#issuecomment-429555026], which, imo, should be resolved before releasing

**Comment by danhenryten** [comment]
Hi, yes can we address @rsichny fix or suggestion to be included with the new release, since we have having problems with the periodic tasks firing sporadically, in which was resolved by using @rsichny fix.

**Comment by pgrzesik** [comment]
Hey there, any updates on the next release ?

**Comment by auvipy** [comment]
@thedrow any chance?

**Comment by thedrow** [comment]
I released 1.3.0.
