### ISSUE TITLE
Periodic Task 'expires' only supports expiring tasks at a specific time, should support seconds as well

### ISSUE THREAD

**Issue by insertjokehere** [celery/django-celery-beat#19]
According to the [docs](http://docs.celeryproject.org/en/v4.0.2/userguide/calling.html#expiration) it should be possible to set a number of seconds after the task is published for it to be expired instead of a fixed datetime. To me this seems like the more useful of the two for periodic tasks; as in "run this task every minute, but if this instance takes more than 90 seconds to get to the top of the queue, consider it stale and don't run it"

**Comment by shapiromatron** [comment]
I just ran into the same issue. Could it be saved as a timedelta perhaps, which would be added to the time the task is sent? I don't really understand the use-case to have an interval based periodic task with a constant expiration date for all tasks.

**Comment by elka0711** [comment]
Same Problem, actual it is only possible to run the beat without:
 --scheduler django_celery_beat.schedulers:DatabaseScheduler
use standard Scheduler (with configs from the script) run's 100% with option expire.
But that's not the solution for the future
