### ISSUE TITLE
Can't create a task with interval from the admin panel

### ISSUE THREAD

**Issue by c1rdan** [celery/django-celery-beat#193]
I can't add a task with an interval from the admin panel, it raises ValidationError as solar is also present when it's not. I could create the same PeriodicTask from django shell.

![image](https://user-images.githubusercontent.com/1965374/47708408-47711600-dc2e-11e8-98ea-aab1f81508c9.png)

**Comment by bruceskyaus** [comment]
I have the same error too with version 1.2.0. Tried using master branch but it still doesn't allow a save. Will need to work around by inserting rows manually using SQL.

**Comment by c1rdan** [comment]
> 
> 
> I have the same error too with version 1.2.0. Tried using master branch but it still doesn't allow a save. Will need to work around by inserting rows manually using SQL.

No need to use SQL, you can add them with python, however, I found another issue where the task is not executing...

**Comment by c1rdan** [comment]
I had downgraded to 1.1.1 and both this issue and the one with PeriodicTasks not executing at all are solved.

**Comment by GamePad64** [comment]
So, the bug have been merged in #38.

**Comment by thedrow** [comment]
This should be fixed in 1.3.0.
