### ISSUE TITLE
PeriodicTask.expires as timedelta and not absolute date [feature request]

### ISSUE THREAD

**Issue by kobymeir** [celery/django-celery-beat#209]
I wish to schedule tasks every hour, However i don't want the tasks to pile up in the queue in case the worker stops working.
It would be much easier to set them to be expired after 50-60 minutes from their creation time.
so if the worker does start again all of the tasks (except the last one) will be expired.

**Comment by pptime** [comment]
willing to help

**Comment by liquidpele** [comment]
That's a good concept!  Please send us a PR if you can get it working and we'll take a look!

**Comment by pptime** [comment]
it's been integrated in an internal project, i will see how I could or not extract it.

**Comment by m-hu** [comment]
Does #281 solve this issue? The implementation is slightly different, but my feeling is that this issue has not been taken into account yet?
