### ISSUE TITLE
Issue with Django USE_TZ=False and TIME_ZONE set

### ISSUE THREAD

**Issue by Sovetnikov** [celery/django-celery-beat#211]
The situation:
celery 4.2.1
django-celery-beat 1.4.0
Django 2.1.3
Python 3.7
Postgres 9

django settings.py:
TIME_ZONE = 'Europe/Moscow'
USE_TZ = False

> celery report
software -> celery:4.2.1 (windowlicker) kombu:4.2.2 py:3.7.1
billiard:3.5.0.5 redis:3.0.1
platform -> system:Linux arch:64bit imp:CPython
loader -> celery.loaders.app.AppLoader
settings -> transport:redis results:django-cache
result_backend: 'django-cache'
task_serializer: 'pickle'
accept_content: ['json', 'pickle']
result_serializer: 'pickle'
timezone: 'Europe/Moscow'
result_expires: datetime.timedelta(days=14)
task_track_started: True
broker_url: 'redis://redis:6379/1'
worker_log_color: False
worker_max_tasks_per_child: 50
worker_prefetch_multiplier: 1

The project is using naive datetime and i know what i'm doing.

The problem is that task with period of 1 minute schedule is started constantly by beat in loop.

> beat_1 | [2018-12-19 09:00:54,575: DEBUG/MainProcess] .tasks.server_tasks.tasks_scheduler sent. id->03755bc5-3cfc-408d-928c-69092e8f09cb
beat_1 | [2018-12-19 09:00:54,586: INFO/MainProcess] Scheduler: Sending due task (tasks.server_tasks.tasks_scheduler)
beat_1 | [2018-12-19 09:00:54,588: DEBUG/MainProcess] .tasks.server_tasks.tasks_scheduler sent. id->3ecb6d84-ec1a-4684-bece-90d10c4f2bd8
beat_1 | [2018-12-19 09:00:54,600: INFO/MainProcess] Scheduler: Sending due task (.tasks.server_tasks.tasks_scheduler)
beat_1 | [2018-12-19 09:00:54,602: DEBUG/MainProcess] .tasks.server_tasks.tasks_scheduler sent. id->5981449a-2626-48f1-90ab-0ff6d17ba5de
beat_1 | [2018-12-19 09:00:54,611: INFO/MainProcess] Scheduler: Sending due task (.tasks.server_tasks.tasks_scheduler)

In postgres times stored as UTC and my connection has right timezone set.
My datetime fields is always has local value in local timezone as set in settings.py.

After debugging i see that problem is that celery.beat.Scheduler.is_due always returns negative values and task is started at every tick.

I see that few function dealing with time conversion that beat is using undercover. It is:
celery.utils.time.make_aware
celery.utils.time.maybe_make_aware
django_celery_beat.utils.make_aware

django_celery_beat.utils.make_aware - works fine, depends on USE_TZ. If USE_TZ is False it doing nothing, if True it makes assumption that naive time is UTC and converts it to local timezone.

celery.utils.time.maybe_make_aware is used in celery.schedules.schedule.is_due with last_run_at.
last_run_at in my case is naive time already in local timezone! But celery.utils.time.maybe_make_aware thinks it is UTC time.

Django with USE_TZ=False imply that naive time is always local time.
But celery function celery.utils.time.maybe_make_aware thinks that naive time is always UTC time and makes wrong conversion.

I think core problem is that celery makes "wrong" assumption on naive time timezone, but never mind...

The fix, i think, is that django-celery-beat must take this into account and convert all naive time to UTC when passing to celery functions.

**Comment by Sovetnikov** [comment]
Seems that this version of make_aware resolves my issue:
```
def make_aware(value, timezone=None, is_dst=None):
    """Make a naive datetime.datetime in a given time zone aware."""
    if timezone is None:
        timezone = get_current_timezone()
    if hasattr(timezone, 'localize'):
        # This method is available for pytz time zones.
        return timezone.localize(value, is_dst=is_dst)
    else:
        # Check that we won't overwrite the timezone of an aware datetime.
        if is_aware(value):
            raise ValueError(
                "make_aware expects a naive datetime, got %s" % value)
        # This may be wrong around DST changes!
        return value.replace(tzinfo=timezone)
```

**Comment by MirrorInFolwer** [comment]
> 似乎这个版本的utils.make_aware解决了我的问题：
> 
> ```
> def make_aware(value):
>     """Force datatime to have timezone information."""
>     if getattr(settings, 'USE_TZ', False):
>         # naive datetimes are assumed to be in UTC.
>         if timezone.is_naive(value):
>             value = timezone.make_aware(value, timezone.utc)
>         # then convert to the Django configured timezone.
>         default_tz = timezone.get_default_timezone()
>         value = timezone.localtime(value, default_tz)
>     else:
>         # naive datetimes are assumed to be in local timezone.
>         if timezone.is_naive(value):
>             value = timezone.make_aware(value, timezone.get_default_timezone())
>     return value
> ```
Excuse me, version number.

How to use it?

**Comment by 0xStarcat** [comment]
:+1: seeing same issue

**Comment by costela** [comment]
Nice sleuthing, @Sovetnikov .
Additionally, if you have `DJANGO_CELERY_BEAT_TZ_AWARE=False` (introduced in #203 ), `make_aware` won't even be called, which I'm not sure is the right behavior in this context.
When passing data from django to celery, we basically *have* to make datetimes timezone aware, because otherwise - as you pointed out - celery will do it on its own and it won't know about django's `TIME_ZONE` setting, so it wrongly assumes UTC.

As far as I can tell `make_aware` is only used in this context, so your (@Sovetnikov ) suggested changes should be safe, and the check for `DJANGO_CELERY_BEAT_TZ_AWARE` could be taken out at this point.

Thoughts?
