### ISSUE TITLE
INFO:django_celery_beat.schedulers:Writing entries... logged every 3 minutes

### ISSUE THREAD

**Issue by viperfx** [celery/django-celery-beat#218]
I see this log message from the celery beat worker, every 3 minutes.

Is there a reason for this? I do not see what could be causing the writes on DB.

I am using the latest version of the library.

**Comment by afansv** [comment]
Any news here?

**Comment by viperfx** [comment]
Oh I just stopped using celery with this library. I had many more issues other than this. Just is not worth the trouble if you are building a production service.

**Comment by hibare** [comment]
@viperfx What is the alternative library you are using?

**Comment by auvipy** [comment]
version?

**Comment by jun0jang** [comment]
same issue on 1.5.0. celery beat make task infinitely

**Comment by ax-golubev** [comment]
We also used this libriary and we have got this bug. Version is 2.0.0.

**Comment by JorgenPhi** [comment]
Same here. Version 2.0.0

@auvipy Can we reopen this?

**Comment by JorgenPhi** [comment]
It may just be as simple as making it a debug? Not sure if sync() should not be called that often, but if so this will make me happy :) https://github.com/celery/django-celery-beat/pull/342
