### ISSUE TITLE
Scheduler is mis-firing some tasks

### ISSUE THREAD

**Issue by viperfx** [celery/django-celery-beat#219]
My work load is not too crazy, compared to have I heard from other teams and read online. I'm currently curing celery beat with django-celery-beat so that I can have my tasks managed by the DB (postgres). This allows users to change schedules dynamically.

This past weekend I did a upgrade of my codebase from py2 to py3, and I switched from huey to celery and use native celery beat to handle scheduling.
Previously, I was doing a dumb loop to check for scheduled in a task that fired every minute.

I know... its not great but here is what I did.
```
#run every minute
def conditionally_run_other_tasks():
    # query database and see if some tasks should be run.
    # call the tasks in here and they will be enqueued and executed
```

Hence why I was really glad to move away from that. Having said that though, that little loop only missed a beat a couple of times a month.

I deployed celery yesterday and it has already **missed 5 tasks out of 40.** 

I believe I am on the latest and greatest.
```
celery==4.2.1
django-celery-beat==1.4.0
Django==2.1.4
```

So celery should be using redis as the broker and django-celery-beat should be using Django ORM with Postgres for storing the schedules.

I have datadog logging a bunch of stuff. I can show you some interesting graphs.

**No tasks were dispatched between 4am and 7am UTC**

![image](https://user-images.githubusercontent.com/328257/51488122-bfa13080-1d72-11e9-9771-568e6681d603.png)

Latency and and requests, seem pretty normal
![image](https://user-images.githubusercontent.com/328257/51488177-d9427800-1d72-11e9-935b-14a88625508f.png)

Queries are being run around that time too
![image](https://user-images.githubusercontent.com/328257/51488194-e65f6700-1d72-11e9-81c8-ce2fcb74fa26.png)

So the scheduler did not send the task, I believe.

Any comments or ideas you might have about why it might be happening or what I could do for debugging would be really great.

**Comment by vvoody** [comment]
Same here, I also upgraded Python 2 to Python 3.

```
Python 3.6.8

Django==1.11.18
celery==4.1.1  # stay on 4
django-celery-beat==1.4.0
django-celery-monitor==1.1.2
django-celery-results==1.0.4
```

I even lost some whole hours of a task should be run every 30 seconds.
And not only the task in screenshots but also any other periodic tasks. Never having this kind of issue before upgrade from Celery 3.1.25 to Celery 4.

No tasks run between 2:06 p.m. to 3:05 p.m.:
![image](https://user-images.githubusercontent.com/65963/52827878-835ab900-3101-11e9-8afd-13d933083ee2.png)

No tasks run between 3:39 p.m. to 4:40 p.m.:
![image](https://user-images.githubusercontent.com/65963/52827884-86ee4000-3101-11e9-9cb6-fede57ca9871.png)

**Comment by vvoody** [comment]
Now it's 2019-02-14 21:39. I found my Celery beat stopped half a hour ago and never wake up.

![image](https://user-images.githubusercontent.com/65963/52834844-b9f2fc80-311e-11e9-90c0-d19a779155eb.png)

**Comment by auvipy** [comment]
same in celery 4.3?

**Comment by viperfx** [comment]
I've honestly stopped using celery and this extension for db related scheduling. It just isn't reliable.

**Comment by PhamLeHai** [comment]
I had a similar issue, that the Celery beat just stops from 4 AM to 12 AM.
I noticed that at 12 AM after the backend_cleanup task finished, other tasks can continue to process.

I found it was due to the Timezone settings. The backend_cleanup task is initialized as UTC (ignore the timezone setting), while other tasks are GTM+8.

When scheduling task, the cleanup task is triggered at 4 AM (at GTM+8), which is fine, but it is not actually processed until 12 AM (at GTM+8). So I think there was a bug here, related to using the timezone value of crontab when triggering and processing tasks.

Btw, I changed the backend_cleanup task to GMT+8, things are working fine now.

@viperfx Can you check your case? I suspect it is similar.

**Comment by moseb** [comment]
#224 might be related

**Comment by PhamLeHai** [comment]
It seems Celery will reset the timezone of the Backend_cleanup task back to UTC upon initialization, so changing the timezone is not a long term solution.

**Comment by kareemsuhail** [comment]
@viperfx what is the alternative you used ?

**Comment by auvipy** [comment]
did you try the latest release or master branch? did anyone check the related code to figure out the root cause?
