### ISSUE TITLE
Django 2.1 support

### ISSUE THREAD

**Issue by barseghyanartur** [celery/django-celery-beat#220]
Any hope for Django 2.1 support soon?

**Comment by timmygee** [comment]
Where does it say celery beat does not support 2.1? Asking because I'm trying to get it working on Django 2.1 as we speak 😬

**Comment by timmygee** [comment]
I have this working with Django 2.1

Make sure you have 100% followed these instructions for setting up your celery beat worker

http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html#using-custom-scheduler-classes
