### ISSUE TITLE
Add locking to ensure only one celery beat server runs at any time

### ISSUE THREAD

**Issue by chdsbd** [celery/django-celery-beat#229]
I think it would be useful to add a locking feature that insures only one celery beat server runs at any time, similar to what [redbeat](https://github.com/sibson/redbeat#why-redbeat) provides via redis.

**Comment by auvipy** [comment]
PR welcome

**Comment by liquidpele** [comment]
I'm generally against locking at the app level like this, what if you have multiple beat servers running on the same host but using different celery clusters?   Deciding what processes should start is more of an installation/os level decision, i.e. done via systemd or init or whatever.

**Comment by liquidpele** [comment]
If you want to create a PR I'd take a look, but it would have to allow multiple beat processes somehow since that's a possible use case even if it's not the typical one.
