### ISSUE TITLE
Minor bug in celery utils.time.py file

### ISSUE THREAD

**Issue by esh-b** [celery/django-celery-beat#235]
There is a function named `remaining` in the `celery.utils.time.py` file. In that function, I think the statement `start = start.replace(tzinfo=now.tzinfo)` (line 211) has to be replaced with `start = start.astimezone(now.tzinfo)`. 

I hope the expected working by using the statement (`start = start.replace(tzinfo=now.tzinfo)`) is to change the `start` variable's datetime according to the `now` variable's timezone. But the `replace` function in the above mentioned statement is just replacing the timezone of the `start` variable without changing the values of datetime in it. I thought  `astimezone` is the method required for our purpose (which converts the datetime in `start` variable to the given timezone argument).

Please correct me incase I am wrong.

**Module versions:**
Python 3.5.2
celery==4.2.1
django-celery-beat==1.4.0

**Comment by auvipy** [comment]
PR welcome

**Comment by esh-b** [comment]
celery/celery#5411

**Comment by auvipy** [comment]
Thanks fixed merged there going to delete this as duplicate.
