### ISSUE TITLE
Issue with crontab to run every `x` days

### ISSUE THREAD

**Issue by ajaykmr2292** [celery/django-celery-beat#236]
I would like to know whether `crontab` can be used to run every 3 days from the current day. Also, suppose the last day of the month is 31, then after running on `30th`, the next run must be on `2nd` and not `3rd` (as is the case with crontab since it runs for every date divisible by 3). 

As you can see, if the month has date `31`, then the gap will be 4 days and not 3 days. So, I would like to know whether crontab can do it.

I assume it cant. So, I was trying to use `IntervalSchedule` model to run every `x` days. But I would like to know whether I could use `IntervalSchedule` to run every `x` days at specified time (like say run every 2 days at 11AM). Please tell me how to do this.

**Comment by esh-b** [comment]
I dont think `django_celery_beat` has the feature for running the task every n days at specific time (you want to run the task every 2 days at 1PM). So, one workaround for scheduling for EXACTLY `every n days` at **SPECIFIC TIME** is like this:

1. The type of schedule to use is `IntervalSchedule`. This would run the task every 'n' days at the time when its scheduled (its the time when you are saving the scheduling and NOT your expected time of run of your scheduled task). For example, if you are scheduling the task using `IntervalSchedule` at 11.30AM (time of saving the schedule), the scheduler will run the task every n days at 11.30AM.
2. To run the schedule at a specific time (for example, you want to run the task every 2 days at 1PM), first create a datetime object (`timezone.now()` in django) and replace the `hour` and `minute` values to your expected scheduled time of run (1PM). Then, save the `last_run_at` column value in the `IntervalSchedule` with the created datetime object. 
3. Now, this will run your schedule every n days at your SPECIFIC time.

Hope this helps.
