### ISSUE TITLE
django celery run twice on scheduled task 

### ISSUE THREAD

**Issue by adikshirsagar** [celery/django-celery-beat#238]
I have same task execute at morning and at evening CELERYBEAT_SCHEDULE tasks

'send_shoot_summary_morning': {
        'task': 'scheduler.tasks.send_shoot_summary',
        'schedule': crontab(hour=4, minute=0, day_of_week="0-5"),
    },
    'send_shoot_summary_evening': {
        'task': 'scheduler.tasks.send_shoot_summary',
        'schedule': crontab(hour=18, minute=00, day_of_week="0-5"),
    },
but morning task execute twice at 4 am and 4:03 am 
celery version is 3.1.25
django version 1.8
python version 2.7
redis-server  v=3.2.5

**Comment by helloagain-dev** [comment]
For how long does your task run approximately?
Are these the only 2 tasks you are running? Do you use one_off tasks?
Maybe it is related to this issue I have: https://github.com/celery/django-celery-beat/issues/222

**Comment by adikshirsagar** [comment]
@helloagain-dev  10-15 mails send , takes 1-2 minute most.

**Comment by auvipy** [comment]
celery version is 3.1.25
django version 1.8 this are not supported in this library. so I am closing this and moving this to django-celery
