### ISSUE TITLE
Python 3 versions support status

### ISSUE THREAD

**Issue by sireliah** [celery/django-celery-beat#251]
### Summary:
What is the roadmap for supporting newer versions of Python 3?
Currently we support:
```
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.4
    Programming Language :: Python :: 3.5
```
I saw some work by @liquidpele here: https://github.com/celery/django-celery-beat/pull/243 to make tests compatible ith Python 3.7. When the library is planned to officially support Python > 3.5?

If there is any blocker, I can help myself with porting the code.

**Comment by auvipy** [comment]
https://github.com/celery/django-celery-beat/blob/master/setup.py

**Comment by liquidpele** [comment]
If you're talking about the readme, I think it gets that info from pypi, so it'll update once we cut a new version.

**Comment by sireliah** [comment]
Thanks for the update!
