### ISSUE TITLE
TypeError: Object of type 'UTC' is not JSON serializable

### ISSUE THREAD

**Issue by springgreenner** [celery/django-celery-beat#253]
### Summary:

Include a *brief* descrioption of the problem here, and fill out the version info below.  

* Celery Version: 4.3.0
* Celery-Beat Version: 1.4.0
* django :2.2
* rest-framework:3.9.2

### Exact steps to reproduce the issue:
I use drf, serializer error, TypeError: Object of type'UTC'is not JSON serializable, how can I solve it?

### Detailed information

Please include more detailed information here, such as relevant information about your system setup, things you did to try and debug the problem, log messages, etc.

**Comment by auvipy** [comment]
This is a drf issue.
