### ISSUE TITLE
Expose PeriodicTask.last_run_at in Django admin, at least read-only?

### ISSUE THREAD

**Issue by moseb** [celery/django-celery-beat#256]
Hi!

It seems that `PeriodicTask.last_run_at` is not exposed to Django admin. I get that modifying it might produce hick-ups but being able to see it would ease debugging sometimes.

What do you think?

**Comment by liquidpele** [comment]
Sure, send us a PR and we'll have a look!

**Comment by hartwork** [comment]
Should be fixed. Can this be closed?
