### ISSUE TITLE
shared_task defined in custom apps not showing up in registered tasks in periodic tasks admin page

### ISSUE THREAD

**Issue by pramttl** [celery/django-celery-beat#26]
The tasks defined in the `proj/proj/celery.py` file directly are registering successfully.

However, shared tasks defined in the custom django apps are not registering to the database and not showing up in admin at `/admin/django_celery_beat/periodictask/`.

**proj/proj/celery.py**

```
# .. imports.. #
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'proj.settings')

celery_app = Celery('proj')
celery_app.config_from_object('django.conf:settings', namespace='CELERY')
celery_app.autodiscover_tasks()

@celery_app.task(bind=True)
def hello():
    print "This task is registering successfully"
```

**proj/app/tasks.py**
```
from celery import shared_task

@shared_task
def app_hello():
    print "This task is not registering"
```

**Comment by pramttl** [comment]
I think, this could be because of the celery `autodiscover_tasks` not working.

**Comment by pramttl** [comment]
Sorry, this issue has nothing to do with `django-celery-beat`.  Just for anyone's reference who hits this issue page in future, I'll describe what solved the issue for me.  I had not replaced `django.conf:settings` in the celery.py file with the django `settings` variable.

In `proj/proj/celery.py`, this line:
```
celery_app.config_from_object('django.conf:settings', namespace='CELERY')
```

Should be,
```
celery_app.config_from_object(settings, namespace='CELERY')
```

Don't forget the`from django.conf import settings` at the top of the file.

**Comment by Teketel** [comment]
`celery_app.config_from_object(settings, namespace='CELERY')`
Don't forget thefrom django.conf import settings at the top of the file.
This does not work for me

**Comment by tsantor** [comment]
I agree, this issue has nothing to do with `django-celery-beat` as I am experiencing the same issue, but have not been able to find a solution anywhere.  The bound task in `celery.py` is found, but the shared tasks in any `appname/tasks.py` files are not found.

**Comment by dagnaldo** [comment]
@tsantor try to add on your `proj/proj/__init__.py`

```
from .celery import celery_app
```

**Comment by diemus** [comment]
@dagnaldo thanks , it works

**Comment by chrisconlan** [comment]
@dagnaldo and his answer should be in the quick start guide. Been using celery for a year and never had to reach for this solution before.

**Comment by kishorpawar** [comment]
> @tsantor try to add on your `proj/proj/__init__.py`
> 
> ```
> from .celery import celery_app
> ```

It is imported as said in the quick start guide, but still `shared_task` is not showing up. 
Though importing `django.conf.settings` fixed recurrsion error.

**Comment by srini-pen** [comment]
from django.conf import settings

app.config_from_object(settings)

It's working for me and able to able to see shared_task

**Comment by Ronnie08** [comment]
> @tsantor try to add on your `proj/proj/__init__.py`
> 
> ```
> from .celery import celery_app
> ```

it works, thanks a lot

**Comment by UlrichEschcol** [comment]
> @tsantor try to add on your `proj/proj/__init__.py`
> 
> ```
> from .celery import celery_app
> ```

it works for me. Great. Thanks

**Comment by DevilsAutumn** [comment]
Hi, I am facing a similar problem ,tried both the above solutions but they didn't work.
backend/celery.py
```
import os

from celery import Celery
from django.conf import settings


from config.redis import redis_instance

# Set the default Django settings module for the 'celery' program.
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "backend.settings")

ri = redis_instance()

app = Celery("backend")

# Using a string here means the worker will not have to
# pickle the object when using Windows.
app.config_from_object(settings, namespace="CELERY")

# Load task modules from all registered Django app configs.
app.autodiscover_tasks()

@app.task(bind=True)
def hello():
    print ("This task is registering successfully")
```
backend/backend/__init__.py
```
from .celery import app as celery_app

__all__ = ('celery_app',)
```

 I have my task in `backend/app/tasks.py` and its not showing up in registered tasks without importing in `view.py`

**Comment by jb9474** [comment]
`sudo systemctl restart gunicorn`
For those running nginx gunicorn as a proxy, reloading gunicorn after changing tasks definitions was the only solution to register up to date tasks in django admin.
