### ISSUE TITLE
Clocked tasks won't execute

### ISSUE THREAD

**Issue by alternativshik** [celery/django-celery-beat#266]
### Summary:
Clocked tasks not run from beat. 

* Celery Version: 4.3.0
* Celery-Beat Version: 1.5

### Exact steps to reproduce the issue:
1. Created clocked schedule.
2. Create periodic task with On-OFF enabled and selected clocked schedule
3. Beat logs says that Schedule was changed
4. At selected time task don't execute

### Detailed information
I'm using correct timezones for celery and for django project, if I select interval or crontab schedule for tasks - they run fine.

**Comment by liquidpele** [comment]
@yywing This was your feature iirc.

**Comment by hartwork** [comment]
Related: #226 / https://github.com/celery/django-celery-beat/pull/226/files

**Comment by hartwork** [comment]
Hi @alternativshik ,

I played with the clocked schedule myself now — I could not reproduce the issue that you describe.
Are you sure that both the clocked schedule and the periodic task are (still) enabled? Pull request #268 might help to inspect `ClockedSchedule.enabled` live.

**Comment by alternativshik** [comment]
@hartwork yep, Schedule was not enabled and this flag was not present in django admin.

**Comment by hartwork** [comment]
@alternativshik excellent, thanks for the update!

**Comment by ajaykrprajapati** [comment]
Hi team,

I am also facing the same issue, I am doing the same thing.. my clockedTime is same but not sending messages. What could be the reason?
I see for one cloackedtime, multiple periodic_task is being created ... is this the issue?
@hartwork @alternativshik 
![error1](https://user-images.githubusercontent.com/11367145/94119941-2a224200-fe6d-11ea-816a-d872092b6616.png)

**Comment by hungnt2-TT** [comment]
I am also facing the same situation with running PERIODIC TASKS. Is there a way to fix that now?
