### ISSUE TITLE
[1.5.0] clockedschedule.py redefines celery.schedules.schedstate of Celery >=3.1.0?

### ISSUE THREAD

**Issue by hartwork** [celery/django-celery-beat#267]
Hi!

I noticed this code:
https://github.com/celery/django-celery-beat/blob/db68a4997420e141b002b555d0d58e98f32a6a4f/django_celery_beat/clockedschedule.py#L10

I would expect `from celery.schedules import schedstate` instead, which requires Celery >=3.1.0.

Is there need to support Celery <3.1.0? otherwise, I would suggest to turn this into an import, e.g. to be safe towards future use of `isinstance` that would fail for non-obvious reasons.

What do you think?

CC @yywing

**Comment by hartwork** [comment]
Any thoughts?

**Comment by liquidpele** [comment]
Personally, I wouldn't want to break backward compatibility on purpose, especially for something so minor.  If you want though, we could do something like this:
    
    # schedstate importable with celery >= 3.1.0
    try:
        from celery.schedules import schedstate
    except ImportError
        schedstate = namedtuple('schedstate', ('is_due', 'next'))

**Comment by hartwork** [comment]
Let's do that, see #273
