### ISSUE TITLE
Add a "Run now" admin action on the scheduled tasks ?

### ISSUE THREAD

**Issue by kedare** [celery/django-celery-beat#28]
Hello,

Would it be interesting to add a "Run now" admin action on the scheduled task? So we could easily run tasks without having to use the shell. This should be quite easy to implement.

Thanks.
Mathieu

**Comment by auvipy** [comment]
a PR is welcome

**Comment by bradshjg** [comment]
@auvipy #52

**Comment by PlugaruT** [comment]
In the admin interface, this action doesn't show up.

**Comment by bradshjg** [comment]
@PlugaruT what are the available actions in the "Action" menu on the "Periodic tasks" page?

**Comment by PlugaruT** [comment]
@bradshjg, only delete action.

**Comment by bradshjg** [comment]
@PlugaruT it looks like the issue is different than missing the "run now" action, you should be seeing the following actions:

* Delete selected periodic tasks
* Enable selected periodic tasks
* Disable selected periodic tasks
* Run selected periodic tasks

**Comment by PlugaruT** [comment]
my bad, I have updated to the latest version and now everything is ok. Thanks!
