### ISSUE TITLE
Consider adding django-test-migrations

### ISSUE THREAD

**Issue by sobolevn** [celery/django-celery-beat#290]
I know that `django-celery-beat` [had](https://github.com/celery/django-celery-beat/issues/217) some [issues](https://github.com/celery/django-celery-beat/issues?utf8=%E2%9C%93&q=is%3Aissue+migration) with migrations back in the days.

I am proposing to add the support of testing migration files to prevent errors like:
1. Inconsistent migrations order, like here: https://github.com/celery/django-celery-beat/blob/master/django_celery_beat/migrations/0006_periodictask_priority.py#L9
2. Possibly incompatible changes to existing models in a complex migrations, like this one: https://github.com/celery/django-celery-beat/blob/master/django_celery_beat/migrations/0010_auto_20190429_0326.py#L22

This can be done with the help of https://github.com/wemake-services/django-test-migrations

I would be glad to hear your feedback if any.

**Comment by liquidpele** [comment]
I added tests because of those issues, see https://github.com/celery/django-celery-beat/blob/master/t/unit/test_models.py#L14

Also the tox file now does these tests starting from various versions so there's full coverage.

**Comment by auvipy** [comment]
new migrations tests are added to the project
