### ISSUE TITLE
django-timezone-field breaking celery-beat on Python 3 and Django 1.11

### ISSUE THREAD

**Issue by karangupta31** [celery/django-celery-beat#296]
### Summary:

With the release of django-timezone-field v4.0, the support for django 1.11 has been dropped. 
https://github.com/mfogel/django-timezone-field

* Celery-Beat Version: 1.4.0 and 1.5.0

### Exact steps to reproduce the issue:
1. Setup project on Django 1.11 and Python 3.7
2. Install django-celery-beat
3. django-timezone-field breaks as it doesn't support django 1.11. 

### Detailed information

With the release of django-timezone-field v4.0, the support for django 1.11 has been dropped. Hence for the above environment, the package breaks.

**Comment by auvipy** [comment]
we will drop Django 1.11 soon as well

**Comment by karangupta31** [comment]
> we will drop Django 1.11 soon as well

But before we do, there needs to be a stable release for the above environment. And hence the need for the fix.

**Comment by D3X** [comment]
> we will drop Django 1.11 soon as well

@auvipy I created a PR for this: #300

**Comment by D3X** [comment]
@auvipy I think this issue can be closed
