### ISSUE TITLE
Tasks won't get executed if DatabaseScheduler updated 

### ISSUE THREAD

**Issue by arbazkiraak** [celery/django-celery-beat#313]
I noticed that whenever we update or add an entry to `PeriodicTask`, the scheduler will make update  & with status `DatabaseScheduler: Schedule changed` which seems to block the execution of next interval tasks.

```
→ pip3 freeze | grep "celery"
celery==4.4.0
django-celery-beat==1.6.0

→ python3 -V
Python 3.7.6

→ django-admin version
2.2.4
```

Any workarounds?

**Comment by brunopastor** [comment]
This is happening to me as well. I tried decorators and database entries. Same result as OP.

Any help is greatly appreciated.

**Comment by auvipy** [comment]
Happen in master as well?

**Comment by auvipy** [comment]
closing for the lack of feedback.
