### ISSUE TITLE
Periodic Tasks scheduled via crontab sending duplicate tasks 8 hours apart

### ISSUE THREAD

**Issue by bk-equityzen** [celery/django-celery-beat#319]
### Summary:

Include a *brief* descrioption of the problem here, and fill out the version info below.  

* Celery Version: 4.4.0
* Celery-Beat Version: 1.6.0

kombu: 4.6.7
amqp: 2.5.2

Previous version that did not have this issue:
celery==4.3.0
django-celery-beat==1.5.0
kombu==4.6.5
amqp==2.5.1

### Exact steps to reproduce the issue:
1. `USE_TZ` is False
2. Schedule a task that runs once everyday (e.g. 00 9 * * * )
3. The task runs twice a day. Seems like ~8 hours before the actual scheduled time and then at the actual scheduled time.

### Detailed information

Please include more detailed information here, such as relevant information about your system setup, things you did to try and debug the problem, log messages, etc.  

My timezone is ET (UTC-5). 1.5.0 did not have this issue. I use naive datetimes. celery timezone and django timezome are both `America/New_York`

**Comment by auvipy** [comment]
were you able to reproduce with latest celery and django-celery-beat?
