### ISSUE TITLE
when i remove django_celery_beat_periodictask, the task already loop run

### ISSUE THREAD

**Issue by chestarss** [celery/django-celery-beat#321]
### Summary:

Include a *brief* descrioption of the problem here, and fill out the version info below.  

* Celery Version: 4.4.1
* Celery-Beat Version: 2.0.0

### Exact steps to reproduce the issue:
I add period task by " PeriodicTask.objects.create(interval=schedule,   name='loop approval', task='xxxxx')  "
beat works
but when I do delete from django_celery_beat_periodictask
the beat task already do loop

when i remove django_celery_beat_periodictask, the task already loop run

### Detailed information

Please include more detailed information here, such as relevant information about your system setup, things you did to try and debug the problem, log messages, etc.

**Comment by auvipy** [comment]
did v2.2 fix your issue somehow?
