### ISSUE TITLE
Celery Beat doesn't execute the tasks after upgrade 2.0.0

### ISSUE THREAD

**Issue by wayhome25** [celery/django-celery-beat#323]
### Summary:
* Celery Version: 4.4.1
* Celery-Beat Version: 2.0.0
* python: 3.6.4
* Django: 2.2.9

### Exact steps to reproduce the issue:
1. just upgrade celerybeat package (1.5.0 -> 2.0.0)
2. right after upgrading celerybeat, all periodic tasks were not executed anymore.

### Detailed information
- Log : There was no error log, celerybeat cervice was ok
- Settings: CELERY_TIMEZONE = 'Asia/Seoul' (Timezone setting was same always)

**Comment by sourabhvarshney111** [comment]
Did you find any solution? I am facing same issue. If so, please tell. Thanks in advance.
