### ISSUE TITLE
AppRegistryNotReady when i used DatabaseScheduler

### ISSUE THREAD

**Issue by Shailendranjain** [celery/django-celery-beat#328]
### Summary:

Running beat with default scheduler (-s) works fine.

However running beat with custom scheduler ( -S django) resulting in below errors.

raise AppRegistryNotReady(‘Apps aren’t loaded yet’)

django.core.exception.AppRegistryNotReady: Apps aren’t loaded yet

* Celery Version: 4.0.0
* Celery-Beat Version: 1.0.1

Although it is older version ( because I need to use django 1.11.6 with other dependency) , can you please advise why I am not able to start celery beat ?

Note: I am able to access the django-celery-beat tables through django admin. 

### Exact steps to reproduce the issue:
1. 
2. 
3. 

### Detailed information

Please include more detailed information here, such as relevant information about your system setup, things you did to try and debug the problem, log messages, etc.

**Comment by liquidpele** [comment]
Well, that error means you're trying to use django without running django.setup()

**Comment by Shailendranjain** [comment]
Can you please advise where do I need to add the django.setup()  ? Can you please share one example?

**Comment by Shailendranjain** [comment]
Currently I am running celery beat as below

{virtualenvironment}/bin/celery beat -S django -A project —loglevel=DEBUG

However I am not sure where to call django.setup() 

I tried adding the line in wsgi.py but it did not help

**Comment by liquidpele** [comment]
Well, celery doesn't require django... but beat does.  So between when celery is importing and using beat, there needs to be a django.setup(), otherwise django will not allow you to utilize the models/etc since it hasn't initialized its installed_apps.   Could be a bug?

**Comment by Shailendranjain** [comment]
The other thing needs to be noted here is that beat with default scheduler (with -s option ) does not throw this error

**Comment by Shailendranjain** [comment]
Figured out that the app names defined in django project had to be preceded with project name.

Thanks liquidpele  for your help with this
