### ISSUE TITLE
celery.backend_cleanup never executing

### ISSUE THREAD

**Issue by okfish** [celery/django-celery-beat#33]
Any schedule defined via admin page of django-celery-beat must have `queue` and `exchange` fields being set explicitly. Otherwise, it wouldn't be executed. So, we need to change the built-in celery.backend_cleanup schedule to have this options. That's ok.
As of a bug #7 we will restart celery-beat to enable changed schedules. This action performs a call of [install_default_entries()](https://github.com/celery/django-celery-beat/blob/master/django_celery_beat/schedulers.py#L189) which overwrites our changes made before, so the task wont execute.
Adding something like
```
CELERY_BEAT_SCHEDULE = {
        'celery.backend_cleanup': {
            'options': {'expires': 12 * 3600, 'queue': 'default', 'exchange': 'default'},
    },
}
```
seems not to be working: task will be overwritten with hardcoded defaults on each celery-beat restart.

I'm using celery 4.0.2 and master branch of django-celery-beat with django-db result backend, if it makes sense. Other tasks works as expected, also. The only problem is backend_cleanup execution.

**Comment by fpalamour** [comment]
I was wondering why I had this task pushed every day in the default celery queue not being consumed. Is that a big deal leaving it unconsumed in the no longer used default queue ?
