### ISSUE TITLE
No module named 'celery.utils.time'

### ISSUE THREAD

**Issue by dezmaeth** [celery/django-celery-beat#334]
### Summary:

No module named 'celery.utils.time'

* Celery Version: 3.3.1
* Celery-Beat Version: 2.0.0

### Exact steps to reproduce the issue:
1. create virtualenv , pip install following packages
```
django==3.0.5
six==1.13.0
celery==3.1.25
django-celery>=3.3.1
django-celery-beat==2.0.0
```
2. start django with manage command

### Detailed information
```
 File "/home/maeth/.pyenv/versions/galactus/lib/python3.6/site-packages/django_celery_beat/clockedschedule.py", line 4, in <module>
    from celery.utils.time import maybe_make_aware
ModuleNotFoundError: No module named 'celery.utils.time'
```

**Comment by triopter** [comment]
Have you tried uninstalling django-celery and upgrading celery to 4.x?  That worked for me when encountering a similar error today.
