### ISSUE TITLE
Req-Enable sorting on Task name

### ISSUE THREAD

**Issue by gainskills** [celery/django-celery-beat#336]
### Summary:
A feature request: enable sorting on "periodic task" column

Include a *brief* descrioption of the problem here, and fill out the version info below.  

* Celery Version: 4.4.2     
* Celery-Beat Version: 2.0.0

### Exact steps to reproduce the issue:
1. Navigate Periodic tasks page on Django admin site
2. It doesn't support sorting on column 'Periodic Task' 

### Detailed information

admin.py -> class PeriodicTaskAdmin -> list_display reference `'__str__'` 
```
    list_display = ('__str__', 'enabled', 'interval', 'start_time',
                    'last_run_at', 'one_off')
```

Can it enable sorting on the column? I did a try in this way:
1. define another def for the filed:
```
    def task_str(self, obj):
        return obj.__str__()

    task_str.short_description = 'Periodic Task'
    task_str.admin_order_field = 'name'
```

2. replace '__str__' with the new field:
```
    list_display = ('task_str', 'enabled', 'interval', 'start_time',
                    'last_run_at', 'one_off')
```

![image](https://user-images.githubusercontent.com/1937472/80159290-b8746c80-861e-11ea-8c95-5e07d49b8313.png)

Thanks,

**Comment by auvipy** [comment]
did this work for you? I never tried this way

**Comment by gainskills** [comment]
> did this work for you? I never tried this way

Yes, I did a try and it works for me while I was creating the ticket.

**Comment by auvipy** [comment]
so you want to contribute back this back? what extra benefits does this provide? it would be great if you could provide a unit test for the proposed change as well

**Comment by gainskills** [comment]
> so you want to contribute back this back? what extra benefits does this provide? it would be great if you could provide a unit test for the proposed change as well

sure, let me do this.

**Comment by mg64ve** [comment]
@gainskills was this implemented?

**Comment by gainskills** [comment]
@mg64ve , verified with the version: v2.5.0, the req has been supported already.
<img width="706" alt="image" src="https://github.com/celery/django-celery-beat/assets/1937472/cdb58f00-785e-4903-8149-1a5187362382">
