### ISSUE TITLE
Tasks Status is always pending

### ISSUE THREAD

**Issue by sourabhvarshney111** [celery/django-celery-beat#340]
### Summary:
 The status of a task is always pending when beat is running.

* Celery Version: 4.4.2
* Celery-Beat Version: 2.0.0 

### Exact steps to reproduce the issue:
Django Celery settings are:
#Celery
CELERY_BROKER_URL = 'amqp://guest@localhost:5672/'
CELERY_RESULT_BACKEND = 'rpc://'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_IGNORE_RESULT = False
CELERY_TASK_TRACK_STARTED = True
CELERYBEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

If there is any specific configuration I need to set, then please tell

**Comment by auvipy** [comment]
could you please try more new release and report again?

**Comment by sourabhvarshney111** [comment]
Will try again and report.

Thanks
