### ISSUE TITLE
[question]get periodic_task_id in shared_task

### ISSUE THREAD

**Issue by fenghaoyu** [celery/django-celery-beat#343]
Sorry to ask here.
Im new to celery,now i got a problem.
Is there any way to get current django_celery_beat_periodictask object or id in shared_task ?
```
@shared_task
def start_task(itemId):
    record_obj= Record()

    # i want to record which periodictask this record_obj belong to.
    record_obj.periodictask = <periodictask>

    record_obj.save()
    return True
```
Any help is useful,thank you!

**Comment by auvipy** [comment]
first, you have to check https://docs.djangoproject.com/en/dev/topics/db/queries/#retrieving-a-single-object-with-get and make yourself familiar with Django ORM well. then you can query on celery beat models as you want. hope that was helpful.
