### ISSUE TITLE
the default timezone of CrontabSchedule should not be a hardcode

### ISSUE THREAD

**Issue by belongwqz** [celery/django-celery-beat#345]
### Summary:

the default timezone of CrontabSchedule current is 'UTC', can it keep the same with CELERY_TIMEZONE dynamically.  

* Celery Version: 4.4.3
* Celery-Beat Version: 2.0.0

### Exact steps to reproduce the issue:
1. open `xxx/admin/django_celery_beat/crontabschedule/add/ `  to add a crontabschedule
2. the Cron Timezone is UTC

### Detailed information

when is write `CELERY_TIMEZONE = 'Asia/Shanghai'` in the settings.py of my projects，can the timezone of CrontabSchedule is 'Asia/Shanghai' but not 'UTC'

**Comment by belongwqz** [comment]
What's more, the `CELERY_` prefix comes from `app.config_from_object('django.conf:settings', namespace='CELERY')`, it might be changed.

**Comment by auvipy** [comment]
can you review the linked PR?

**Comment by belongwqz** [comment]
OK, see my review.
