### ISSUE TITLE
 No module named 'django-celery-beat'

### ISSUE THREAD

**Issue by rinyshen** [celery/django-celery-beat#349]
### Summary:

Include a *brief* descrioption of the problem here, and fill out the version info below.  

* Celery Version: 
* Celery-Beat Version: 

### Exact steps to reproduce the issue:
1.  celery 4.4.5
2. django-celery-beat: 2.0.0
3. 

### Detailed information

when I executed command: python manage.py migrate , I got errors:   No module named 'django-celery-beat'

**Comment by auvipy** [comment]
> When you add the django-celery-beat to installed apps in settings it should be `django_celery_beat` **not** `django-celery-beat`

that is it. closing as per this.
