### ISSUE TITLE
Celery beat running periodic task even after the given crontab schedule

### ISSUE THREAD

**Issue by waqashamid** [celery/django-celery-beat#354]
I've been trying to debug my way into figuring out why my beat triggers tasks even after the time they're not supposed to run.

So, I want to run a task every 15 mins from let's say 10am to 11pm and I have done this:

1. Made an entry into django_celery_beat_periodictask like:

```
# id, name, task, args, kwargs, queue, exchange, routing_key, expires, enabled, last_run_at, total_run_count, date_changed, description, crontab_id, interval_id, solar_id, one_off, start_time, priority, headers, clocked_id, expire_seconds
20, foo, app.tasks.foo, [], {}, , , , , 0, , 271, 2020-07-14 23:08:15, foo, 38, , , 0, , , {}, , 

```

2. The `38` above is an FK to `django_celery_beat_crontabschedule` which is a crontab specifying the run times, which looks like:

```
# id, minute, hour, day_of_week, day_of_month, month_of_year, timezone
'38', '*/15', '10-23', '*', '*', '*', 'Asia/Kolkata'
```

That's how my `foo` looks like:

```
@task()
def foo():
    print("Hello World")
    logger.info("Factorial of 5 {}".format(math.factorial(5)))
    print("Hello World")
```

These are the versions of the packages I'm using:
```
celery==4.3.0
django-celery-beat==1.5.0
django-redis==4.8.0
redis==3.3.8
Django==2.2.10
```

My config for django celery looks like:
```
import logging
import os
from logging.handlers import RotatingFileHandler

from celery import Celery
from celery.signals import after_setup_logger
from django.conf import settings

from celtest.settings import LOG_DIR

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'celtest.settings')
logger = logging.getLogger(__name__)
app = Celery('celtest')

app.config_from_object('django.conf:settings')

app.conf.task_default_queue = 'celtest-celery'

app.conf.update(
    timezone=settings.TIME_ZONE,
    enable_utc=False,
    beat_scheduler=settings.BEAT_SCHEDULER,
    task_serializer='pickle',
    result_serializer='pickle',
    accept_content=['pickle'],
)

# Load task modules from all registered Django app configs.
app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)


@after_setup_logger.connect
def setup_loggers(logger, *args, **kwargs):
    formatter = logging.Formatter('[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s')
    file_handler = RotatingFileHandler(f'{LOG_DIR}/celery.log', backupCount=10, maxBytes=1024 * 1024 * 100)
    logger.addHandler(file_handler)


@app.task(bind=True)
def debug_task(self):
    print('Request: {0!r}'.format(self.request))
```

Now, the problem that I am facing is, my cron runs even after 11pm.

I tried changing that to 5pm or 3pm. It doesn't seem to cause any effect on beat - which schedules it anyway every 15 mins.

I restart my celery and beat every time after making changes inside my crontab above.

How do you guys debug stuff like these? Is there an approach? What's going wrong here?

**Comment by it-devel-att-hais** [comment]
I think you must register your tasks in **app.conf.beat_schedule**
```
app.conf.beat_schedule = {
    'trigger_news': {
        'task': 'trigger_news',
        'schedule': crontab(minute='*/5'), 
    },
    'delete_old_news': {
        'task': 'delete_delete_old_news',
        'schedule': crontab(minute=0, hour=6),
    }
}
```
And run your celery-beat with **django_celery_beat.schedulers:DatabaseScheduler** arg. Example
```
celery -A your_app beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
```

**Comment by auvipy** [comment]
> I think you must register your tasks in **app.conf.beat_schedule**
> 
> ```
> app.conf.beat_schedule = {
>     'trigger_news': {
>         'task': 'trigger_news',
>         'schedule': crontab(minute='*/5'), 
>     },
>     'delete_old_news': {
>         'task': 'delete_delete_old_news',
>         'schedule': crontab(minute=0, hour=6),
>     }
> }
> ```
> 
> And run your celery-beat with **django_celery_beat.schedulers:DatabaseScheduler** arg. Example
> 
> ```
> celery -A your_app beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
> ```

hope this helps to resolve the issue.
