### ISSUE TITLE
Celery beat stopped working suddenly

### ISSUE THREAD

**Issue by xxholyChalicexx** [celery/django-celery-beat#358]
### Summary:

Include a *brief* descrioption of the problem here, and fill out the version info below.  

* Celery Version: 4.4.0
* Celery-Beat Version: 4.4.0

### Exact steps to reproduce the issue:
Not sure

### Detailed information

My celery beat stopped working out of nowhere and i could only see this message. No other error but only this in the log
`celerybeat.service - Celery Service
   Loaded: loaded (/etc/systemd/system/celerybeat.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2020-08-25 06:40:47 UTC; 16min ago
  Process: 21165 ExecStart=/bin/sh -c ${CELERY_BIN} beat     -A ${CELERY_APP} --pidfile=${CELERYBEAT_PID_FILE}    --logfile=${CELERYBEAT_LOG_F
 Main PID: 21165 (code=exited, status=1/FAILURE)`

**Comment by rtician** [comment]
I have a issue kind like that, my celery beat stop working out of nowhere. I was using the celery 4.4.0 and django-celery-beat 1.5.0.

Already tried to upgrade the packages to celery 5.0.0 and django-celery-beat 2.0.0, but no success. If I remove the database scheduler and try to run the beat with the default scheduler it works.

Any help is welcome

**Comment by rakesh-ridecell** [comment]
I saw the same issue with celery 4.4.0, celery beat stops working for some time but resumes after some time. I've seen it stopping for ~1hr and then continuing again. Not sure about the exact steps to reproduce this.

**Comment by thedrow** [comment]
Please refer to the migration guide and release notes.
We removed the ability to specify `-A` as part of the sub-command's options.

The deamonization guide has also been updated.
If you have any further questions, please let me know.
