### ISSUE TITLE
crontab schedule with specific time not running

### ISSUE THREAD

**Issue by subha-py** [celery/django-celery-beat#36]
When I am setting a **specific time like 1:04 or 23:11** as hours and minutes and all other fields are *. The scheduler is getting updated but not sending the task to celery worker.
But if I set the hour and minutes with respect to ***/{any number}**, it is running well. The day_of_week parameter is also working. Just the specific-time cron periodic tasks are not getiing scheduled.
Using django 1.11, celery/master and django-celery-master.
Any solution would be very much helpful.

**Comment by subha-py** [comment]
Example creating crontab-based periodic task

in readme not working @auvipy @ask

**Comment by hobbes7878** [comment]
Would love to see a response to this one. Same problem.

**Comment by liberza** [comment]
Also having this issue.

**Comment by RabidCicada** [comment]
Believe this is related to #57 and I think a fix is incoming in work on #56 all originally spurred by #55
