### ISSUE TITLE
Not compatible with celery 5.0.0

### ISSUE THREAD

**Issue by he0119** [celery/django-celery-beat#364]
### Summary:

When go to admin periodictask page, these is an error. 

* Celery Version: 5.0.0
* Celery-Beat Version:  2.0.0

### Exact steps to reproduce the issue:
1.  Login to admin page
2.  Click Periodic tasks
3.  Boom

### Detailed information

<details><summary>LOGS</summary>
<p>
Environment:

Request Method: GET
Request URL: http://localhost:8000/admin/django_celery_beat/periodictask/

Django Version: 3.1.1
Python Version: 3.8.5
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'user_sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'mptt',
 'import_export',
 'graphene_django',
 'django_celery_beat',
 'storage',
 'board',
 'xiaoai',
 'iot',
 'corsheaders']
Installed Middleware:
['corsheaders.middleware.CorsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'user_sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback (most recent call last):
  File "C:\Users\hmy01\Works\Working\smart-home\.venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\hmy01\Works\Working\smart-home\.venv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hmy01\Works\Working\smart-home\.venv\lib\site-packages\django\contrib\admin\options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\hmy01\Works\Working\smart-home\.venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\hmy01\Works\Working\smart-home\.venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\hmy01\Works\Working\smart-home\.venv\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\hmy01\Works\Working\smart-home\.venv\lib\site-packages\django_celery_beat\admin.py", line 156, in changelist_view
    extra_context['wrong_scheduler'] = not is_database_scheduler(scheduler)
  File "C:\Users\hmy01\Works\Working\smart-home\.venv\lib\site-packages\django_celery_beat\utils.py", line 42, in is_database_scheduler
    from .schedulers import DatabaseScheduler
  File "C:\Users\hmy01\Works\Working\smart-home\.venv\lib\site-packages\django_celery_beat\schedulers.py", line 11, in <module>
    from celery.utils.encoding import safe_str, safe_repr

Exception Type: ModuleNotFoundError at /admin/django_celery_beat/periodictask/
Exception Value: No module named 'celery.utils.encoding'
</p>
</details>

**Comment by mrteera** [comment]
Same problem here
```

**Comment by perlcloud** [comment]
Same issue when trying to set up: https://github.com/pydanny/cookiecutter-django

**Comment by itmanagerkrim** [comment]
Getting the same error.

**Comment by drippypale** [comment]
same error here.

**Comment by Jitjo** [comment]
fixed it by changing 'celery.utils.encoding' to 'kombu.utils.encoding'

**Comment by samsonarita** [comment]
> 'celery.utils.encoding' to 'kombu.utils.encoding'

This one worked for me.

**Comment by robertpro** [comment]
@tuky worked for me.

**Comment by auvipy** [comment]
should be fixed on master now, please check and let us know

**Comment by tuky** [comment]
thx @auvipy. the `from kombu.utils.encoding import safe_str, safe_repr` import now made it into `schedulers.py` twice.

**Comment by galileoguzman** [comment]
I'm getting the same error when I run 

```

celery -A proj beat -l INFO --scheduler django
celery -A proj beat -l INFO -S django

celery -A proj beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
celery -A proj beat -l INFO -S django_celery_beat.schedulers:DatabaseScheduler
```

But when I run

```
celery -A proj beat -l INFO
```

But the results is
```
LocalTime -> 2020-10-15 22:16:10
Configuration ->
    . broker -> amqp://guest:**@localhost:5672//
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> celery.beat.PersistentScheduler
    . db -> celerybeat-schedule
    . logfile -> [stderr]@%INFO
    . maxinterval -> 5.00 minutes (300s)
[2020-10-15 22:16:10,468: INFO/MainProcess] beat: Starting...
```
Eventhough I set the `beat_scheduler ` setting. The settings in _lowecase_ do not work by the way.

I have the same stack @he0119 has.

**Comment by Tjorriemorrie** [comment]
Commenting this out gives no error:
# CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

**Comment by ckleemann** [comment]
@auvipy This fix works for me. Are there any plans to release a new version on pypi which fix this bug?

**Comment by auvipy** [comment]
v2.1.0 is now on pypi

**Comment by ckleemann** [comment]
v2.1.0 works with Celery v5.0.0 in my setup the issue is resolved and can be closed.

**Comment by m3nu** [comment]
Also updated and the combo works fine.
