### ISSUE TITLE
from /admin/django_celery_beat/periodictask/ url,it's err, look imgs

### ISSUE THREAD

**Issue by Duchongc** [celery/django-celery-beat#372]
### Summary:

Include a *brief* descrioption of the problem here, and fill out the version info below.  

* Celery Version: 4.4.7
* Celery-Beat Version: 2.0.0

### Exact steps to reproduce the issue:
1. from /admin/django_celery_beat/periodictask/, return err, 2,look imgs, thanks
2. 
3. 

### Detailed information

Please include more detailed information here, such as relevant information about your system setup, things you did to try and debug the problem, log messages, etc.

**Comment by auvipy** [comment]
can you please add ore detail? your report doesn't meet the standard
