### ISSUE TITLE
Latest Version of django-timezone-field breaks django-celery-beat

### ISSUE THREAD

**Issue by omarsumadi** [celery/django-celery-beat#377]
Hello,

I wrote a more detailed issue at this link:
https://github.com/pydanny/cookiecutter-django/issues/2950

Generally, the owner of django-time-zone updated today (Nov. 28th, 2020) their package to version 4.1.1, which broke the migration 0013_auto_20200609_0727.py.

The reason this happened is two fold however, since you guys have https://github.com/celery/django-celery-beat/blob/master/requirements/default.txt saying: "django-timezone-field>=4.0,<5.0", so when he/she updated their pypi, django-celery-beat installation from pip pulled the latest version of django-timezone-field instead of the stable version, which breaks this package since it now uses the latest 4.1.1 version. 

Mandating django-timezone-field==4.0 in my requirements.txt file fixes the issue.

Thanks,
Omar

**Comment by auvipy** [comment]
it would be great if you could either pin or send a patch with the new  version released

**Comment by davidrothera** [comment]
I'm working on a fix now, should be fairly trivial

```
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 829, in get_default
    return self._get_default()
  File "/usr/local/lib/python3.8/site-packages/django_celery_beat/models.py", line 60, in crontab_schedule_celery_timezone
    choice[0].zone for choice in timezone_field.TimeZoneField.CHOICES
AttributeError: type object 'TimeZoneField' has no attribute 'CHOICES'
```

**Comment by omarsumadi** [comment]
@davidrothera Thanks for making that fix - I'm a github noob (as you can see by my history) and still learning the basics. Very glad that someone with more experience like you filled in.

Thanks!

**Comment by ohld** [comment]
Just got the same error and can't wait for #378 to be merged. Thank you @davidrothera for the fix! 
![image](https://user-images.githubusercontent.com/5613295/100597269-4a0f2f80-330e-11eb-9bea-b037578a15ad.png)
