### ISSUE TITLE
how can i change PeriodicTask and get all data from task in database?

### ISSUE THREAD

**Issue by GarridoM** [celery/django-celery-beat#379]
I have a doubt about PeriodicTask Class. I would like to add other field to database or overwrite this class with other one. Is any way to do that?

Another doubt, how can I pass the task object to the function of that task? I mean,  I want to get all the data that there is in the database related with the task that is executing in each moment.

**Comment by auvipy** [comment]
In an ideal scenario, we should provide an abstract base model class that can be easy to modify. but now you need to check the codes and do it yourself carefully. https://github.com/openwisp/django-swappable-models

**Comment by yashikakhurana** [comment]
To create my own scheduler, I did something like this 

`  class PeriodicTask(django_celery_beat.models.PeriodicTask)` and added new fields to this class.
