### ISSUE TITLE
Periodic task with crontab in admin not running on 2.1.0

### ISSUE THREAD

**Issue by lucianofedericoolmedo** [celery/django-celery-beat#380]
### Summary:
Periodic tasks not that actually running in the admin. 
When creating Interval Schedule or Cron Schedule periodic tasks, those tasks are not running:
The only ones that work seems to be clocked interval ones.  

* Celery Version: 4.4.6
* Celery-Beat Version: 2.1.0 

### Exact steps to reproduce the issue:
1. Select to create a periodic task
2. Assign a function to execute
3. Assing a 1 minute crontab schedule | or every one minute.

### Detailed information
I tried with clocked schedule tasks and works but it is not what i need.

I am using docker, and my docker-compose setup is like this

    worker:
        ....
        command: celery -A MYPROJECT worker -l debug
    beat:
        .....
        command: celery -A MYPROJECT beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler

**Comment by cbrews** [comment]
@lucianofedericoolmedo can you provide a bit more information as to what's in your celery configuration in `settings.py`?  I ran into this issue today, but was able to get it resolved.

I'm running a slightly different version from you--and I know that there are some minor incompatibilities between celery 4.x.x and celery-beat 2.1.0.  Can you upgrade celery to 5.x.x?  See https://github.com/celery/django-celery-beat/pull/363

You may also want to consider dropping to debug level logging on the beat worker and seeing if something is breaking upstream.

For me, the culprit ended up being that CELERY_BROKER_USE_SSL settings were causing connectivity issues between redis (my backend) & the celery beat worker.  I just removed this and my beat scheduler was able to reconnect.

```python
CELERY_BROKER_URL = 'redis://redis:6379/0'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/New_York'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
```

Couple of things to try.

**Comment by auvipy** [comment]
> @lucianofedericoolmedo can you provide a bit more information as to what's in your celery configuration in `settings.py`? I ran into this issue today, but was able to get it resolved.
> 
> I'm running a slightly different version from you--and I know that there are some minor incompatibilities between celery 4.x.x and celery-beat 2.1.0. Can you upgrade celery to 5.x.x? See #363
> 
> You may also want to consider dropping to debug level logging on the beat worker and seeing if something is breaking upstream.
> 
> For me, the culprit ended up being that CELERY_BROKER_USE_SSL settings were causing connectivity issues between redis (my backend) & the celery beat worker. I just removed this and my beat scheduler was able to reconnect.
> 
> ```python
> CELERY_BROKER_URL = 'redis://redis:6379/0'
> CELERY_RESULT_BACKEND = 'django-db'
> CELERY_ACCEPT_CONTENT = ['application/json']
> CELERY_TASK_SERIALIZER = 'json'
> CELERY_RESULT_SERIALIZER = 'json'
> CELERY_TIMEZONE = 'America/New_York'
> CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
> ```
> 
> Couple of things to try.

can you share anything we miss that could be included in the docs?

**Comment by auvipy** [comment]
we also got a new release 2.2.0 now

**Comment by suprmat95** [comment]
Hi, I'm matteo. I'm stuck with the same problem of @lucianofedericoolmedo with the only difference that i just upate to **Celery-Beat Version: 2.1.0**
my configuration is:
```
if USE_TZ is True:
    CELERY_TIMEZONE = TIME_ZONE
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default=env("REDIS_URL", default="redis://redis:6379/0"))
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_ACCEPT_CONTENT = ["pickle", "json", "msgpack"]
CELERY_TASK_SERIALIZER = "pickle"
CELERY_TASK_TIME_LIMIT = 60 * 35  # Hard limit of 35 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 60 * 30  # 30 minutes
CELERY_DEFAULT_QUEUE = "celery"
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
```
The odd thing is that it works locally and don't work in production. do you have any hints?

**Comment by ganlanshu** [comment]
> Hi, I'm matteo. I'm stuck with the same problem of @lucianofedericoolmedo with the only difference that i just upate to **Celery-Beat Version: 2.1.0**
> my configuration is:
> 
> ```
> if USE_TZ is True:
>     CELERY_TIMEZONE = TIME_ZONE
> CELERY_BROKER_URL = env("CELERY_BROKER_URL", default=env("REDIS_URL", default="redis://redis:6379/0"))
> CELERY_RESULT_BACKEND = CELERY_BROKER_URL
> CELERY_ACCEPT_CONTENT = ["pickle", "json", "msgpack"]
> CELERY_TASK_SERIALIZER = "pickle"
> CELERY_TASK_TIME_LIMIT = 60 * 35  # Hard limit of 35 minutes
> CELERY_TASK_SOFT_TIME_LIMIT = 60 * 30  # 30 minutes
> CELERY_DEFAULT_QUEUE = "celery"
> CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
> ```
> 
> The odd thing is that it works locally and don't work in production. do you have any hints?

 have the same problem, it works locally and dont's work in production 
 django 2.2.17 
 celery-beat 2.0.0
celery 4.4.5

**Comment by auvipy** [comment]
you need to check your production server settings and environments then
