### ISSUE TITLE
Enabling a disabled task that has passed its execution time causes it to run immediately

### ISSUE THREAD

**Issue by tcosta84** [celery/django-celery-beat#383]
I realized that when I enable a disabled task that has already passed its execution time, it is execute immediately.
Is that the expected behaviour?

I expected it wouldn't run automatically.
I'd like to use this enable/disable option as a a pause/play feature.

* Celery Version: 4.4.2
* Celery-Beat Version: 1.5.0

Exact steps to reproduce the issue:
1. Create a task to run at a given time (eg: 5pm);
2. Disable it;
2. Minutes later, enable it;
3. The task should run immediately.

How can I avoid the task to run automatically.

**Comment by auvipy** [comment]
it seems you are using a very old version. can you please try v2.1/master?
