### ISSUE TITLE
Error migrating with Djongo (MongoDB)

### ISSUE THREAD

**Issue by majonathany** [celery/django-celery-beat#385]
### Summary:

Hi, I have a problem where when I try to run the migrations with Djongo (MongoDB wrapper), and I can't complete the migration. I'm wondering if I can modify the code somehow to get it to work because I think the issue is MongoDB's way of handling changing schema, but I'm unsure how to change it to fix it. Is there a known solution to fix this problem?

* Celery Version: 4.4.7
* Celery-Beat Version: 2.2.0

 

### Exact steps to reproduce the issue:
1. Install Django 3.0.5 with Djongo 1.3.3 and Celery 2.2.0
2. Attempt to migrate into mongodb

### Detailed information
Traceback:

Operations to perform:
  Apply all migrations: account, admin, ai, auth, authtoken, contenttypes, django_celery_beat, django_celery_results, sessions, sites, socialaccount, users
Running migrations:
WARNING 2021-01-19 14:03:15,278 query 48577 4493147648 Not implemented alter command for SQL ALTER TABLE "django_celery_beat_periodictask" ADD COLUMN "solar_id" int NULL
  Applying django_celery_beat.0002_auto_20161118_0346...Traceback (most recent call last):

djongo.exceptions.SQLDecodeError: 

        Keyword: int
        Sub SQL: ALTER TABLE "django_celery_beat_periodictask" ADD COLUMN "solar_id" int NULL
        FAILED SQL: ('ALTER TABLE "django_celery_beat_periodictask" ADD COLUMN "solar_id" int NULL',)
        Params: ([],)
        Version: 1.3.3

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/professional/.virtualenvs/env-jm-local/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/professional/.virtualenvs/env-jm-local/lib/python3.8/site-packages/djongo/cursor.py", line 59, in execute
    raise db_exe from e
djongo.database.DatabaseError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

**Comment by majonathany** [comment]
Hm, I seem to have gotten around this problem by doing 

```
python3 manage.py migrate django_celery_beat 0002_ --fake #fakes the migration
python3 manage.py migrate django_celery_beat 0002_ #continues the migration that point on
```

I'm guessing it's okay because it is MongoDB and there is no schema requirements, and all you need is a table name in Mongo, but I hope it doesn't break anything.

If anyone can verify that this is the best approach to this type of problem, that'd be awesome.

**Comment by auvipy** [comment]
all that I can suggest to you is to use another SQL database in your Django project with multiple DB settings. this library uses Django ORM so I can't share any right solution as Django doesn't support it officially.
