### ISSUE TITLE
(Question) Is there a reason for the Lack of Documentation for One-Off Tasks?

### ISSUE THREAD

**Issue by omarsumadi** [celery/django-celery-beat#391]
### Summary:

I'm in love with django-celery-beat, and it has provided me with so much flexibility for my projects, and it works incredibly well and the existing documentation is easy to read.

However, I can't find any documentation on one-off tasks, and I was wondering why that was the case. Are One-Off tasks not production ready yet or something? They seem fine to me.

If not, I'd be happy to write documentation on how to do it.

### What made me think of this?

For instance, I was surprised to see that a task with a one-off notation still required the scheduler parameter to be set, which is counter intuitive to me because shouldn't a one off task never trigger any sort of scheduler - just rely on the start time?

For instance:
```python 
                PeriodicTask.objects.create(
                    interval=schedule,
                    one_off = True,
                    name = TaskID,
                    description = str(TimeZone),
                    task='edsproject.users.tasks.RatePredictionTask',
                    start_time = ScheduleDateTime,
                    last_run_at = datetime.utcnow() - timedelta(seconds=15), # make sure task gets executed
                    kwargs=json.dumps({'ExecutionList': json.dumps(ExecutionList), 'CPUPower': json.dumps(CPUPower), 'TaskID': TaskID, 'TaskType': TaskType, 'EmailList': json.dumps(FinalEmailList), 'TaskName': TaskName}),
                    )
```

The above works, but if you take off the interval=schedule or contrab=schedule (in which schedule is an IntervalSchedule or Crontab schedule object, the function returns an error.

Thanks,
Omar

**Comment by auvipy** [comment]
periodic tasks are designed to have an interval, so its one of task or lots of you are needed to set interval, but you can dig the codes for having better understanding then share your suggested improvement

**Comment by omarsumadi** [comment]
@auvipy Yeah that makes sense, no change needed - but was still wondering how come this isn't on the Docs anywhere? One-off tasks seem to be extremely useful feature. It should be documented because it's so useful!

Is there a reason / can I help?

**Comment by auvipy** [comment]
you can send docs improvement :)

**Comment by omarsumadi** [comment]
Will do - I have never contributed to Open Source, so let me figure it out
