### ISSUE TITLE
Celery beat is stuck at “writing entries…”. Celery worker is working fine

### ISSUE THREAD

**Issue by MuhammadBilal1** [celery/django-celery-beat#402]
I am starting my celery beat (Django Celery) with the below command but it's not going forward after "writing entries".

But the worker is working fine, running both in separate terminal windows.

`$ celery -A myproject worker -l debug`

I created another sample Django app and in that beat is working fine.

OS: **Ubuntu 20.04**
Celery Version: **5.0.5**

![celery](https://user-images.githubusercontent.com/7131058/115449556-69aee200-a234-11eb-9b51-70f6d6a6b037.png)

**Comment by thedrow** [comment]
Why do you think it is stuck?
See https://github.com/celery/django-celery-beat/blob/master/django_celery_beat/schedulers.py#L292

**Comment by MuhammadBilal1** [comment]
> Why do you think it is stuck?
> See https://github.com/celery/django-celery-beat/blob/master/django_celery_beat/schedulers.py#L292

Thanks for your response, but why this isn't going forward and sending the tasks? While it should send the scheduled tasks.

**Comment by thedrow** [comment]
It seems like the schedule is empty.
I don't have enough information to debug this and this seems like a usage problem.
Please refer to our support channels for help.

**Comment by wojciezki** [comment]
Any updates about this issue?

**Comment by MuhammadBilal1** [comment]
> Any updates about this issue?

I didn't received anything related to this problem yet.

**Comment by mattrei** [comment]
same problem here

**Comment by ChetSocio** [comment]
Yeah it happened in my case when I forgot to add celery beat settings in settings.py file.

**Comment by cclauss** [comment]
Should the code raise an error/warning when no relevant settings are found?  Or are there reasonable defaults for all settings?

**Comment by ChetSocio** [comment]
Hey I learned some points that may be helpful in these cases:
1) Celery doesn't work in windows properly. Same goes to celery beat. Task may be success but not executed
2) Celery fails silently most of the time. 
3) Django Celery beat executes tasks later if it cannot instantly.  I stopped celery workers and tried to run scheduled tasks. It succeeded but didn't run. Once I ran workers again, the left out task executed instantly. 
4) Celery beat works fine with proper settings.  Running tasks from settings.py is old approach and may face bugs. One bug I faced is: the task I was trying to execute always threw `unregistered task named ******* ` error . So i added `CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'` and I created scheduled tasks from admin panel and same task executed correctly with no warnings or error. Note: if i ran the same task using task.delay() as background task, it ran fine. Which means the error was from beat side not celery side.
5) Django celery beat tasks are sometimes shown on flower and sometimes not. Which is tragic in my case.
6) I wanted celery beat to have a dynamic approach where we can schedule tasks dynamically using some functions. It will reduce some overheads. 
Demo config of properly working celery and celery beat:

`mybackened/mybackened/settings.py:`
```
encoded_password = urllib.parse.quote(os.getenv('REDIS_PASSWORD'), safe="")

CELERY_BROKER_URL = f"redis://:{encoded_password}@127.0.0.1:6880/3"
CELERY_RESULT_BACKEND = f"redis://:{encoded_password}@127.0.0.1:6880/4"
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = "Asia/Kathmandu"
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_RESULT_EXTENDED = True   # provides extended details about tasks ad workers
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_WORKER_CONCURRENCY=5
CELERY_TASK_TRACK_STARTED = True
DJANGO_CELERY_BEAT_TZ_AWARE=True
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
```

`mybackened/mybackened/celery.py:`
```
from __future__ import absolute_import, unicode_literals
import os
from celery import Celery
from dotenv import load_dotenv
from django.apps import apps 

load_dotenv()

# Set the default Django settings module for the 'celery' program.
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'mybatchbackened.settings')

app = Celery('mybatchbackened')

# Load task modules from all registered Django apps.
app.config_from_object('django.conf:settings', namespace='CELERY')
app.autodiscover_tasks(lambda: [n.name for n in apps.get_app_configs()])


@app.task(bind=True, ignore_result=True)
def debug_task(self):
    print(f'Request: {self.request!r}')

```
