### ISSUE TITLE
Django deprecation warning

### ISSUE THREAD

**Issue by Jordan-PIM** [celery/django-celery-beat#408]
Django 3.2.2 produces deprecation warning on launch

* Celery Version: 5.0.5
* Celery-Beat Version: 2.0.2

"RemovedInDjango41Warning: 'django_celery_beat' defines default_app_config = 'django_celery_beat.apps.BeatConfig'. Django now detects this configuration automatically. You can remove default_app_config.
  app_config = AppConfig.create(entry)"

**Comment by auvipy** [comment]
will remove when we drop Django 2.2 https://github.com/celery/django-celery-beat/blob/master/django_celery_beat/__init__.py

**Comment by LaurentTreguier** [comment]
Would it make sense to conditionally define `default_app_config` depending on [Django's version](https://github.com/django/django/blob/main/django/__init__.py) ?

**Comment by auvipy** [comment]
yes

**Comment by auvipy** [comment]
fixed
