### ISSUE TITLE
Changelog doesn't mention change in Celery version in 2.2.1

### ISSUE THREAD

**Issue by julienc91** [celery/django-celery-beat#422]
### Summary:

django-celery-beat v2.2.0 required `celery>=4.4,<6.0` ([source](https://github.com/celery/django-celery-beat/blob/v2.2.0/requirements/default.txt)), but in v2.2.1, it's now `celery>=5.0,<6.0` ([source](https://github.com/celery/django-celery-beat/blob/v2.2.1/requirements/default.txt)).

I think this update should be mentioned in the changelog.

**Comment by auvipy** [comment]
please send a PR
