### ISSUE TITLE
Strict restriction on Django version

### ISSUE THREAD

**Issue by Mogost** [celery/django-celery-beat#434]
`django-celery-beat` version `2.2.1` can not been installed with new django alpha version `4.0a1` due to strict restrictions here
https://github.com/celery/django-celery-beat/blob/995a22e6079670a2bd93b7da0132f218f3faa53d/requirements/runtime.txt#L1

**Comment by auvipy** [comment]
ok 4.0a1 is still not supported but thanks for reporting will add that and relax the range

**Comment by auvipy** [comment]
https://github.com/celery/django-celery-beat/pull/435 try from master
