### ISSUE TITLE
Unable to run Celery beat

### ISSUE THREAD

**Issue by richardolazo** [celery/django-celery-beat#439]
### Summary:

* Python Version: 3.7
* Celery Version:  5.1.2
* Celery-Beat Version:  2.2.1

### Detailed information
I'm using Poetry for my virtualenv and upon executing `celery -A app beat -l info -S django`, this error always displays.
`RuntimeError: Model class django_celery_beat.models.SolarSchedule doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.`

`django_celery_beat` already installed and migrated.

Please help. Thank you!

**Comment by pydo** [comment]
@richardolazo Seeing that you closed this bug, I assumed you found a workaround? Would you mind sharing it please :slightly_smiling_face:  ?

**Comment by richardolazo** [comment]
@pydo I found out that on my `celery.py` the `os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'app.settings)` was not properly getting the correct settings env, So my fixed was to explicitly point which settings to use. In my case I did `os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'app.settings.<env>)`.

Hope this helps.
