### ISSUE TITLE
Interval works, crontab does not work

### ISSUE THREAD

**Issue by ionatower** [celery/django-celery-beat#45]
I can't get the crontab to work, no matter what I do including restarting the celery beat, restarting the server. I checked the timezone is Europe/London. Interval always works.

```
django==1.10
celery==4.0.2
django_celery_beat==1.0.1
django_celery_results==1.0.1
kombu==4.0.2
amqp==2.1.4
anyjson==0.3.3
billiard==3.5.0.2
```

celery.py:

```
app = Celery('me')

app.config_from_object('django.conf:settings', namespace='CELERY')

app.conf.timezone = 'Europe/London'
app.conf.beat_scheduler = 'DatabaseScheduler'
app.conf.result_backend = 'django-db'

app.conf.beat_schedule = {

# Calls cellery_add(4,5) every 60 seconds - , expires=10
    'celery_add_test_30_secs': {
        'task': 'lendengine.tasks.celery_add',
        'schedule': 30.0,
        "options": {'queue': 'test2Q'},
        'args': (4, 5),
        "enabled": True,
    },


# test a scheduled run:
'cron_test': {
        'task': 'lendengine.tasks.testcrontask',
        'schedule': crontab(),
        "options": {'queue': 'testcronQ'},
        "enabled": True,
    },

}
```

tasks.py:

```
from web.celery import app as app2

@app2.task(queue='testcronQ', time_limit=7200)
def testcrontask(on_day=15, on_month=5):
    return on_day + on_month

@app2.task(queue='test2Q')
# logger.info('running tasks')
def celery_add(x ,y):
    return x + y + 5

```
Commands:
```
celery -A web beat -l debug -S django
celery -A web worker -l debug -Q testcronQ -n worker1@%%h -Ofair
celery -A web worker -l debug -Q test2Q -n worker1@%%h -Ofair
```

**Comment by subha-py** [comment]
Yes this is a problem. I am also stuck here..

**Comment by fredmonroe** [comment]
i have this problem as well

**Comment by lsaint** [comment]
same here:( 
no fix?

**Comment by fredmonroe** [comment]
i eventually got this to work but i can't remember all the details because i decided not to use celery

i believe there were two things i had to do...
run beat separately (not the built in beat service)
get the timezone set correctly <- this was the one that was hard to figure out but i can't remember what i did now
hope that helps

**Comment by lsaint** [comment]
thanks.  i try to set CELERY_TIMEZONE and CELERY_ENABLE_UTC,  but it doesn't work either.  i'm curious about what do you replace celery?

**Comment by typenil** [comment]
This may be an upstream problem. I'm hitting this issue, but using celery directly (rather than django-celery-beat),

I have a mix of intervals and crontabs. The intervals work; the crontabs don't.
