### ISSUE TITLE
Add support for Django 4.0

### ISSUE THREAD

**Issue by Uninen** [celery/django-celery-beat#465]
First, Thanks for this great project! 👍 

### Summary:

Current django-celery-beat requires Django (>=2.2,<4.0) and hence doesn't install together w/ Django 4.0.

**Comment by tari** [comment]
#435 updated to `<4.1`, so there simply needs to be a new release it seems.

**Comment by Uninen** [comment]
Oh, didn't notice that, good catch 👍

**Comment by dorukgezici** [comment]
Yeah, we are waiting for the release as well.

**Comment by auvipy** [comment]
was on vacation. I will clear my backlogs and release this soon

**Comment by Melevir** [comment]
I'm also waiting for the thing. Say if I can help somehow :)

**Comment by auvipy** [comment]
i have a lots of release to make this week, just released py-amqp v5.0.7. have lil bit more patience in the mean time.

**Comment by omfd** [comment]
@auvipy Thanks for the update! Awaiting the support for django 4.0

**Comment by auvipy** [comment]
in the mean try install from master and report any issues

**Comment by Hesam-Taleghani** [comment]
Is there any updates here?

**Comment by auvipy** [comment]
waiting for django 4.0.1 release which is due tomorrow

**Comment by mvaled** [comment]
@auvipy 

I think we can mark this done.  I've updated one of my apps to Django 4.0 using this repo's master branch and, so far, I haven't witnessed any issue.

**Comment by n6g7** [comment]
master branch seems to work but I'm not a fan of using it in production deployments.
@auvipy is there anything anyone can do to help with the release?

**Comment by auvipy** [comment]
just can you tell that using the master branch with django 4.0.1 create any new no-op migrations?

**Comment by mvaled** [comment]
No migrations were detected.  I'm actually using this:

```
django-celery-beat = { git = "https://github.com/celery/django-celery-beat.git", rev = "fa73034be892052893e4ef17926ef3a5d4a21ea2" }
```

with Django 4.0.1.

**Comment by auvipy** [comment]
thanks, I will try to release both django integration tomorrow. taking rest today as last 2 days and one night I was busy with my wife's medical emergency.

**Comment by AlexDaniel** [comment]
Thank you, @auvipy, take care! Yes, we're also waiting for a release, but it's not as urgent. Thank you for your continuous support and maintenance! ♥

**Comment by root4417** [comment]
Hi there, Thanks for such a great thing. Can you enable Django 4.0 ? Because currently it's not installing with Django 4.0. Please release a version.

**Comment by auvipy** [comment]
I  am little bit fatigue in chilly winter. allow me couple of days for release

**Comment by domdinicola** [comment]
> thanks, I will try to release both django integration tomorrow. taking rest today as last 2 days and one night I was busy with my wife's medical emergency.

hope everything is good, take your time and thanks!

**Comment by root4417** [comment]
@auvipy I hope you are doing well. Is there any update on this issue? When can expect a release?

**Comment by auvipy** [comment]
for those benefited from the celery django integration packages consider donating through https://opencollective.com/celery this will support my time.

**Comment by root4417** [comment]
@auvipy I hope you're doing well. We'd like to know more about this issue. Is there going to be a new release,

**Comment by auvipy** [comment]
you people do me a favor? if possible try to review the open PR's on this milestone, try them locally and left your review.
https://github.com/celery/django-celery-beat/milestone/2

**Comment by mvaled** [comment]
@auvipy I will set aside some time during the week to check #462.  As a matter of fact I'm running with Django 4.0 and Python 3.10 for some time now using 

```
django-celery-beat = { git = "https://github.com/celery/django-celery-beat.git", rev = "fa73034be892052893e4ef17926ef3a5d4a21ea2" }
```

**Comment by insspb** [comment]
@auvipy 
Official support of Django 4 appears only in version 5 of https://github.com/mfogel/django-timezone-field
but current master beat restrict this version, causing conflict if both specified in external project config

**Comment by daggaz** [comment]
@insspb I don't think there's any hard incompatibility with django-timezone-field 5.0. The requirement looks like it's just been pinned to <5 to be safe against future backward incompatibilities.

django-celery-beat [doesn't use](https://github.com/celery/django-celery-beat/search?q=display_GMT_offset) the `display_GMT_offset` kwarg which has been removed in 5.0.

I do note however that django-timezone-field has [dropped support](https://github.com/mfogel/django-timezone-field/#50-2022-02-08) for django 3.0 and 3.1 which means this project presumably should also drop those support for those versions.

**Comment by auvipy** [comment]
https://github.com/celery/django-celery-beat/pull/514

**Comment by juancrescente** [comment]
Is this releasing soon?

**Comment by Hesam-Taleghani** [comment]
I'm still waiting as well, is there anything we can help? @auvipy

**Comment by auvipy** [comment]
you all can pray for me, I am suffering from post covid chronic fatigue :) though I am eating well and taking suppliments, I am not so strong yet. I restarted work today, and I have plans to clear all due releases.

**Comment by auvipy** [comment]
however this https://github.com/celery/django-celery-beat/issues/518 might be a blocker, can anyone confirm?

**Comment by AlexDaniel** [comment]
@auvipy get well! Here I had the damn thing twice, with long-lasting effects also but recovered fully (or so I think).

**Comment by auvipy** [comment]
release a related version good peoples https://pypi.org/project/django-celery-results/2.3.0/ next is this in high prio Q! the delays were totally out of my control :)

**Comment by Uninen** [comment]
Thanks! 🙏

Please don't stress about the releases. This is open source and people have lives. If someone wants to speed up the development, they can contribute either code or money.

**Comment by Hesam-Taleghani** [comment]
> you all can pray for me, I am suffering from post covid chronic fatigue :) though I am eating well and taking suppliments, I am not so strong yet. I restarted work today, and I have plans to clear all due releases.

I have had it too, take care and thank you for your time

**Comment by googlina** [comment]
@auvipy 
Hope you are doing well. 
Just wanted to check if there is any update oh support for 4.0

**Comment by grimzy** [comment]
[Related PR](https://github.com/celery/django-celery-beat/pull/487) was merged although there are still a [few other issues to close](https://github.com/celery/django-celery-beat/milestone/2) before release.

**Comment by NickWillems** [comment]
For people that need a quick but dirty workaround, I managed to get it working with Django 4.0.1 by installing the dependencies manually
`pip install celery==5.2.3 django-timezone-field==4.2.3 python-crontab==2.3.4`
`pip install django-celery-beat==2.2.1 --no-deps`

**Comment by rubiodamian** [comment]
any updates about this?

**Comment by APouzi** [comment]
Where is the donate link? I combed through Github and found nothing. I would love to support this project.

**Comment by charanjit-singh** [comment]
I am looking for support of Django==4.0.3

**Comment by Beenhakker** [comment]
> For people that need a quick but dirty workaround, I managed to get it working with Django 4.0.1 by installing the dependencies manually `pip install celery==5.2.3 django-timezone-field==4.2.3 python-crontab==2.3.4` `pip install django-celery-beat==2.2.1 --no-deps`

django-timezone-field v5 is already release with Django 4 support.

**Comment by Hesam-Taleghani** [comment]
Is there any update here? when we should expect the new version release?

**Comment by auvipy** [comment]
by 30th may hopefully but not before 20th may

**Comment by chaubeyaj98** [comment]
@auvipy really needed this updated coz we are stuck and we need to switch to manual

**Comment by APouzi** [comment]
Its interesting, to those of you who really, need it, are you guys donating to make sure it goes along faster? 
Its one thing to ask that if you are a financialy invested stakeholder, otherwise you guys are just going to have to accept whatever day they fix it......or fork it.

**Comment by RayyanNafees** [comment]
So does Celery now support Django 4+ ?

**Comment by auvipy** [comment]
celery support that for a while now
