### ISSUE TITLE
beat_schedule_filename is created even if Django is selected.

### ISSUE THREAD

**Issue by rh0dium** [celery/django-celery-beat#48]
Hi there,

It appears that the `BEAT_SCHEDULE_FILENAME` is still created even if django-celery-beat is used.  It doesn't appear to be used (based on timestamp changing) but it is still created.  

Low priority but it is confusing to tell whether it's using the django database or not.

FYI - I'm launching this in my test env as follows.

```celery -A celery_app worker --events --beat -S django -l DEBUG```

This command is in alignment with the [docs](http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html#using-custom-scheduler-classes) and it makes sense that it creates the `django.db` as the `-S` option defines the filename.  

To verify that its working I needed to set `BEAT_SYNC_EVERY = 1` and then watch the Django database.

**Comment by rh0dium** [comment]
Actually in looking into this further I think here is a bug in the documentation.

`-S` specifies the `BEAT_SCHEDULE_FILENAME`
`--scheduler` specifies the `BEAT_SCHEDULER`

If I swap in `--scheduler` for `-S` then the filename is not created.  

So this appears to be a bug in the documentation.  

As an aside what I ended up doing is 

```celery -A celery_app worker --events --beat --scheduler django_celery_beat.schedulers:DatabaseScheduler -l DEBUG```

**Comment by rh0dium** [comment]
Have a pull request to update the docs.

**Comment by chrisgrande** [comment]
I'm seeing this exact behavior with --scheduler configured as `django_celery_beat.schedulers:DatabaseScheduler
`  the **celerybeat-scedule.db** file is still created.
