### ISSUE TITLE
b.com

### ISSUE THREAD

**Issue by adrianwebb** [celery/django-celery-beat#497]
### Summary:

Include a *brief* descrioption of the problem here, and fill out the version info below.  

* Celery Version: 
* Celery-Beat Version: 

### Exact steps to reproduce the issue:
1. 
2. 
3. 

### Detailed information

Please include more detailed information here, such as relevant information about your system setup, things you did to try and debug the problem, log messages, etc.

**Comment by auvipy** [comment]
please don't open vague issues which seems to be a spam

**Comment by adrianwebb** [comment]
Sorry I do not know how this happened

**Comment by adrianwebb** [comment]
Please feel free to permanently delete this issue
