### ISSUE TITLE
PeriodicTask can not be triggered, when update enabled=True

### ISSUE THREAD

**Issue by Zoom2016** [celery/django-celery-beat#498]
### Summary:
In a word, If I create a PeriodicTask with enable=False, then, this task can never be scheduled. Even if I update enable=True.

* Celery Version: 5.2.3
* Celery-Beat Version: 2.2.1

### Exact steps to reproduce the issue:
1. Insert a PeriodicTask like this:
`PeriodicTask(name="test", crontab=schedule, task='cronjob.tasks.ipmi_task', enabled=False).save()`
2. Then I enabled this task. However, it never be scheduled.
`PeriodicTask.objects.filter(id=periodic_task_id).update(enabled=True)   # no effect`
3. Otherwise, If I init a task with enabled=True, then update with enabled=False，then update with enabled=True. It worker well.
`PeriodicTask(name="test", crontab=schedule, task='cronjob.tasks.ipmi_task', enabled=True).save()
PeriodicTask.objects.filter(id=periodic_task_id).update(enabled=False)   # another request to disable this task
PeriodicTask.objects.filter(id=periodic_task_id).update(enabled=True)   # another request to enable this task
`

**Comment by auvipy** [comment]
can you please share little bit more detail? what fix did you figure out?

**Comment by 954-Ivory** [comment]
Look this:
https://docs.djangoproject.com/en/4.1/ref/models/querysets/#django.db.models.query.QuerySet.update

_Finally, realize that update() does an update at the SQL level and, thus, does not call any save() methods on your models, nor does it emit the pre_save or post_save signals (which are a consequence of calling Model.save()). If you want to update a bunch of records for a model that has a custom save() method, loop over them and call save(), like this:_
```python
for e in Entry.objects.filter(pub_date__year=2010):
    e.comments_on = False
    e.save()
```

**If you want to trigger `PeriodicTasks.changed()`, don't use `update()`.**
