### ISSUE TITLE
CrontabSchedule ignore TIME_ZONE setting

### ISSUE THREAD

**Issue by millin** [celery/django-celery-beat#5]
I just upgraded my project from 'django-celery' to 'django-celery-beat'.

In my django project TIME_ZONE = 'Europe/Moscow'.
I configured CrontabSchedule as "30 9 * * * (m/h/d/dM/MY)", but it was executed only at 12:30.
Why timezone ignored? last_run_at was None, task was launched first time.

**Comment by mheppner** [comment]
I set `CELERY_TIMEZONE = TIME_ZONE` because I'm not sure if Celery 4 even looks at the non-prefixed setting name.

**Comment by aircino** [comment]
I had exactly the same problem... and set CELERY_TIMEZONE resolved my problem too. This issue need to be fixed because in celery docs is written that "For Django users the time zone specified in the TIME_ZONE setting will be used".

**Comment by RabidCicada** [comment]
Indeed...The setting is ignored but documented to be used.  Can we get a resolution?  Either doc update to state this is NOT the case or code update to match docs?
