### ISSUE TITLE
Documentation build is failing

### ISSUE THREAD

**Issue by Kirade** [celery/django-celery-beat#508]
### Summary:

Documentation version still remains at version 1.5.0.
Build fail started 2 years ago.

As shown in log, build script still using python 2.7.
Maybe docs admin could change that script to use proper python version.

Build fail log
https://readthedocs.org/projects/django-celery-beat/builds/15950456/

Is there anything that I can help you, please let me know :)

**Comment by auvipy** [comment]
need to check it properly actually

**Comment by odigity** [comment]
I'm new to django-celery-beat, am using v2.2.1, noticed the out-of-date docs, came here to ask about that, and found this issue.  Commenting so I get notifications.

BTW - I'm confused about PeriodicTasks.  It only has two fields (ident, last_update), and the docstring says "stores a single row with ident=1", which means the only purpose of the entire table is to store a single datetime value, but then the docs homepage says "whenever you update a PeriodicTask a counter in this table is also incremented", which doesn't seem to match the first description or the schema.
