### ISSUE TITLE
zoneinfo.ZoneInfo' object has no attribute 'normalize'

### ISSUE THREAD

**Issue by TobiasEdqvist** [celery/django-celery-beat#518]
### Summary:

When starting a celery beat container with latest master the following is seen in our logs. Are we missing some dependency?

[celery-beat-container] [2022-02-27 19:21:52,007: INFO/MainProcess] beat: Starting...
[celery-beat-container] [2022-02-27 19:21:52,045: CRITICAL/MainProcess] beat raised exception <class 'AttributeError'>: AttributeError("'zoneinfo.ZoneInfo' object has no attribute 'normalize'")
[celery-beat-container] Traceback (most recent call last):
[celery-beat-container]   File "/usr/local/lib/python3.10/site-packages/celery/apps/beat.py", line 105, in start_scheduler
[celery-beat-container]     service.start()
[celery-beat-container]   File "/usr/local/lib/python3.10/site-packages/celery/beat.py", line 645, in start
[celery-beat-container]     interval = self.scheduler.tick()
[celery-beat-container]   File "/usr/local/lib/python3.10/site-packages/celery/beat.py", line 343, in tick
[celery-beat-container]     self.populate_heap()
[celery-beat-container]   File "/usr/local/lib/python3.10/site-packages/celery/beat.py", line 317, in populate_heap
[celery-beat-container]     is_due, next_call_delay = entry.is_due()
[celery-beat-container]   File "/usr/local/lib/python3.10/site-packages/django_celery_beat/schedulers.py", line 136, in is_due
[celery-beat-container]     return self.schedule.is_due(last_run_at_in_tz)
[celery-beat-container]   File "/usr/local/lib/python3.10/site-packages/django_celery_beat/tzcrontab.py", line 45, in is_due
[celery-beat-container]     rem_delta = self.remaining_estimate(last_run_at)
[celery-beat-container]   File "/usr/local/lib/python3.10/site-packages/celery/schedules.py", line 610, in remaining_estimate
[celery-beat-container]     return remaining(*self.remaining_delta(last_run_at, ffwd=ffwd))
[celery-beat-container]   File "/usr/local/lib/python3.10/site-packages/celery/schedules.py", line 548, in remaining_delta
[celery-beat-container]     now = self.maybe_make_aware(self.now())
[celery-beat-container]   File "/usr/local/lib/python3.10/site-packages/celery/schedules.py", line 67, in now
[celery-beat-container]     return (self.nowfun or self.app.now)()
[celery-beat-container]   File "/usr/local/lib/python3.10/site-packages/django_celery_beat/tzcrontab.py", line 31, in nowfunc
[celery-beat-container]     return self.tz.normalize(
[celery-beat-container] AttributeError: 'zoneinfo.ZoneInfo' object has no attribute 'normalize'

* Celery-Beat Version: master branch as of 2022-02-27

**Comment by auvipy** [comment]
we are yet to move to zoneinfo

**Comment by AntoninRousset** [comment]
I confirm

**Comment by piraka9011** [comment]
What needs to be done to move this forward? Is it just replace `pytz` with `zoneinfo`?

**Comment by tremechus** [comment]
As a workaround put this in your Settings.py:

`DJANGO_CELERY_BEAT_TZ_AWARE=False`

This short circuits out the need for the normalize call
