### ISSUE TITLE
NOT AVAILABLE FOR DJANGO 4

### ISSUE THREAD

**Issue by ILLICO-ENTERPRISE** [celery/django-celery-beat#526]
### Summary:

Include a *brief* descrioption of the problem here, and fill out the version info below.  

* Celery Version: 
* Celery-Beat Version: 

### Exact steps to reproduce the issue:
1. 
2. 
3. 

### Detailed information

I work on the new project in my office. And we want to use a PERIODIC TASK but we use django 4.0 and DJANGO CELERY BEAT dont available on DJANGO 4.0. Please upgrade a version constraint of DJANGO to ALLOW HIM.

Thanks

**Comment by sevdog** [comment]
Please refer to #465.
