### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by auvipy** [celery/django-celery-beat#543]
t/unit/test_schedulers.py::test_modeladmin_PeriodicTaskAdmin::test_run_task FAILED [ 57%]
  
  =================================== FAILURES ===================================
  _______________ test_modeladmin_PeriodicTaskAdmin.test_run_task ________________
  
  self = <promise: 0x7f478cc7a790>
  
      def __call__(self):
          try:
  >           return self.__value__
  E           AttributeError: 'ChannelPromise' object has no attribute '__value__'
  
  .tox/py38-django40/lib/python3.8/site-packages/kombu/utils/functional.py:30: AttributeError
  
  During handling of the above exception, another exception occurred:
  
  fun = <bound method Connection._connection_factory of <Connection: ***127.0.0.1:5672// at 0x7f478cc83d00>>
  catch = (<class 'amqp.exceptions.RecoverableConnectionError'>, <class 'OSError'>, <class 'OSError'>, <class 'OSError'>)
  args = [], kwargs = {}
  errback = <function Connection._ensure_connection.<locals>.on_error at 0x7f478cd499d0>
  max_retries = None, interval_start = 2, interval_step = 2, interval_max = 30
  callback = None, timeout = 4
  
      def retry_over_time(fun, catch, args=None, kwargs=None, errback=None,
                          max_retries=None, interval_start=2, interval_step=2,
                          interval_max=30, callback=None, timeout=None):
          """Retry the function over and over until max retries is exceeded.
      
          For each retry we sleep a for a while before we try again, this interval
          is increased for every retry until the max seconds is reached.
      
          Arguments:
              fun (Callable): The function to try
              catch (Tuple[BaseException]): Exceptions to catch, can be either
                  tuple or a single exception class.
      
          Keyword Arguments:
              args (Tuple): Positional arguments passed on to the function.
              kwargs (Dict): Keyword arguments passed on to the function.
              errback (Callable): Callback for when an exception in ``catch``
                  is raised.  The callback must take three arguments:
                  ``exc``, ``interval_range`` and ``retries``, where ``exc``
                  is the exception instance, ``interval_range`` is an iterator
                  which return the time in seconds to sleep next, and ``retries``
                  is the number of previous retries.
              max_retries (int): Maximum number of retries before we give up.
                  If neither of this and timeout is set, we will retry forever.
                  If one of this and timeout is reached, stop.
              interval_start (float): How long (in seconds) we start sleeping
                  between retries.
              interval_step (float): By how much the interval is increased for
                  each retry.
              interval_max (float): Maximum number of seconds to sleep
                  between retries.
              timeout (int): Maximum seconds waiting before we give up.
          """
          kwargs = {} if not kwargs else kwargs
          args = [] if not args else args
          interval_range = fxrange(interval_start,
                                   interval_max + interval_start,
                                   interval_step, repeatlast=True)
          end = time() + timeout if timeout else None
          for retries in count():
              try:
  >               return fun(*args, **kwargs)
  
  .tox/py38-django40/lib/python3.8/site-packages/kombu/utils/functional.py:312: 
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  
  self = <Connection: ***127.0.0.1:5672// at 0x7f478cc83d00>
  
      def _connection_factory(self):
          self.declared_entities.clear()
          self._default_channel = None
  >       self._connection = self._establish_connection()
  
  .tox/py38-django40/lib/python3.8/site-packages/kombu/connection.py:877: 
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  
  self = <Connection: ***127.0.0.1:5672// at 0x7f478cc83d00>
  
      def _establish_connection(self):
          self._debug('establishing connection...')
  >       conn = self.transport.establish_connection()
  
  .tox/py38-django40/lib/python3.8/site-packages/kombu/connection.py:812: 
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  
  self = <kombu.transport.pyamqp.Transport object at 0x7f478cc88f70>
  
      def establish_connection(self):
          """Establish connection to the AMQP broker."""
          conninfo = self.client
          for name, default_value in self.default_connection_params.items():
              if not getattr(conninfo, name, None):
                  setattr(conninfo, name, default_value)
          if conninfo.hostname == 'localhost':
              conninfo.hostname = '127.0.0.1'
          # when server_hostname is None, use hostname from URI.
          if isinstance(conninfo.ssl, dict) and \
                  'server_hostname' in conninfo.ssl and \
                  conninfo.ssl['server_hostname'] is None:
              conninfo.ssl['server_hostname'] = conninfo.hostname
          opts = dict({
              'host': conninfo.host,
              'userid': conninfo.userid,
              'password': conninfo.password,
              'login_method': conninfo.login_method,
              'virtual_host': conninfo.virtual_host,
              'insist': conninfo.insist,
              'ssl': conninfo.ssl,
              'connect_timeout': conninfo.connect_timeout,
              'heartbeat': conninfo.heartbeat,
          }, **conninfo.transport_options or {})
          conn = self.Connection(**opts)
          conn.client = self.client
  >       conn.connect()
  
  .tox/py38-django40/lib/python3.8/site-packages/kombu/transport/pyamqp.py:201: 
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  
  self = <AMQP Connection: 127.0.0.1:5672// (disconnected) at 0x7f478cd5e2e0>
  callback = None
  
      def connect(self, callback=None):
          # Let the transport.py module setup the actual
          # socket connection to the broker.
          #
          if self.connected:
              return callback() if callback else None
          try:
              self.transport = self.Transport(
                  self.host, self.connect_timeout, self.ssl,
                  self.read_timeout, self.write_timeout,
                  socket_settings=self.socket_settings,
              )
  >           self.transport.connect()
  
  .tox/py38-django40/lib/python3.8/site-packages/amqp/connection.py:323: 
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  
  self = <TCPTransport: (disconnected) at 0x7f478cdd78c0>
  
      def connect(self):
          try:
              # are we already connected?
              if self.connected:
                  return
  >           self._connect(self.host, self.port, self.connect_timeout)
  
  .tox/py38-django40/lib/python3.8/site-packages/amqp/transport.py:129: 
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  
  self = <TCPTransport: (disconnected) at 0x7f478cdd78c0>, host = '127.0.0.1'
  port = 5672, timeout = 4
  
      def _connect(self, host, port, timeout):
          entries = socket.getaddrinfo(
              host, port, socket.AF_UNSPEC, socket.SOCK_STREAM, SOL_TCP,
          )
          for i, res in enumerate(entries):
              af, socktype, proto, canonname, sa = res
              try:
                  self.sock = socket.socket(af, socktype, proto)
                  try:
                      set_cloexec(self.sock, True)
                  except NotImplementedError:
                      pass
                  self.sock.settimeout(timeout)
  >               self.sock.connect(sa)
  E               ConnectionRefusedError: [Errno 111] Connection refused
  
  .tox/py38-django40/lib/python3.8/site-packages/amqp/transport.py:184: ConnectionRefusedError
  
  During handling of the above exception, another exception occurred:
  
  self = <t.unit.test_schedulers.test_modeladmin_PeriodicTaskAdmin object at 0x7f478d562df0>
  
      @pytest.mark.timeout(5)
      def test_run_task(self):
          ma = PeriodicTaskAdmin(PeriodicTask, self.site)
          self.request = self.patch_request(self.request_factory.get('/'))
  >       ma.run_tasks(self.request, PeriodicTask.objects.filter(id=self.m1.id))
  
  t/unit/test_schedulers.py:802: 
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  django_celery_beat/admin.py:223: in run_tasks
      task_ids = [
  django_celery_beat/admin.py:227: in <listcomp>
      else task.apply_async(args=args, kwargs=kwargs,
  .tox/py38-django40/lib/python3.8/site-packages/celery/app/task.py:575: in apply_async
      return app.send_task(
  .tox/py38-django40/lib/python3.8/site-packages/celery/app/base.py:788: in send_task
      amqp.send_task_message(P, name, message, **options)
  .tox/py38-django40/lib/python3.8/site-packages/celery/app/amqp.py:510: in send_task_message
      ret = producer.publish(
  .tox/py38-django40/lib/python3.8/site-packages/kombu/messaging.py:177: in publish
      return _publish(
  .tox/py38-django40/lib/python3.8/site-packages/kombu/connection.py:523: in _ensured
      return fun(*args, **kwargs)
  .tox/py38-django40/lib/python3.8/site-packages/kombu/messaging.py:186: in _publish
      channel = self.channel
  .tox/py38-django40/lib/python3.8/site-packages/kombu/messaging.py:209: in _get_channel
      channel = self._channel = channel()
  .tox/py38-django40/lib/python3.8/site-packages/kombu/utils/functional.py:32: in __call__
      value = self.__value__ = self.__contract__()
  .tox/py38-django40/lib/python3.8/site-packages/kombu/messaging.py:225: in <lambda>
      channel = ChannelPromise(lambda: connection.default_channel)
  .tox/py38-django40/lib/python3.8/site-packages/kombu/connection.py:895: in default_channel
      self._ensure_connection(**conn_opts)
  .tox/py38-django40/lib/python3.8/site-packages/kombu/connection.py:433: in _ensure_connection
      return retry_over_time(
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  
  fun = <bound method Connection._connection_factory of <Connection: ***127.0.0.1:5672// at 0x7f478cc83d00>>
  catch = (<class 'amqp.exceptions.RecoverableConnectionError'>, <class 'OSError'>, <class 'OSError'>, <class 'OSError'>)
  args = [], kwargs = {}
  errback = <function Connection._ensure_connection.<locals>.on_error at 0x7f478cd499d0>
  max_retries = None, interval_start = 2, interval_step = 2, interval_max = 30
  callback = None, timeout = 4
  
      def retry_over_time(fun, catch, args=None, kwargs=None, errback=None,
                          max_retries=None, interval_start=2, interval_step=2,
                          interval_max=30, callback=None, timeout=None):
          """Retry the function over and over until max retries is exceeded.
      
          For each retry we sleep a for a while before we try again, this interval
          is increased for every retry until the max seconds is reached.
      
          Arguments:
              fun (Callable): The function to try
              catch (Tuple[BaseException]): Exceptions to catch, can be either
                  tuple or a single exception class.
      
          Keyword Arguments:
              args (Tuple): Positional arguments passed on to the function.
              kwargs (Dict): Keyword arguments passed on to the function.
              errback (Callable): Callback for when an exception in ``catch``
                  is raised.  The callback must take three arguments:
                  ``exc``, ``interval_range`` and ``retries``, where ``exc``
                  is the exception instance, ``interval_range`` is an iterator
                  which return the time in seconds to sleep next, and ``retries``
                  is the number of previous retries.
              max_retries (int): Maximum number of retries before we give up.
                  If neither of this and timeout is set, we will retry forever.
                  If one of this and timeout is reached, stop.
              interval_start (float): How long (in seconds) we start sleeping
                  between retries.
              interval_step (float): By how much the interval is increased for
                  each retry.
              interval_max (float): Maximum number of seconds to sleep
                  between retries.
              timeout (int): Maximum seconds waiting before we give up.
          """
          kwargs = {} if not kwargs else kwargs
          args = [] if not args else args
          interval_range = fxrange(interval_start,
                                   interval_max + interval_start,
                                   interval_step, repeatlast=True)
          end = time() + timeout if timeout else None
          for retries in count():
              try:
                  return fun(*args, **kwargs)
              except catch as exc:
                  if max_retries is not None and retries >= max_retries:
                      raise
                  if end and time() > end:
                      raise
                  if callback:
                      callback()
                  tts = float(errback(exc, interval_range, retries) if errback
                              else next(interval_range))
                  if tts:
                      for _ in range(int(tts)):
                          if callback:
                              callback()
  >                       sleep(1.0)
  E                       Failed: Timeout >5.0s
  
  .tox/py38-django40/lib/python3.8/site-packages/kombu/utils/functional.py:326: Failed
  ------------------------------ Captured log call -------------------------------
  WARNING  kombu.connection:connection.py:629 No hostname was supplied. Reverting to default 'localhost'
  =============================== warnings summary ===============================
  .tox/py38-django40/lib/python3.8/site-packages/django/conf/__init__.py:229
    /home/runner/work/django-celery-beat/django-celery-beat/.tox/py38-django40/lib/python3.8/site-packages/django/conf/__init__.py:229: RemovedInDjango50Warning: The USE_L10N setting is deprecated. Starting with Django 5.0, localized formatting of data will always be enabled. For example Django will display numbers and dates using the format of the current locale.
      warnings.warn(USE_L10N_DEPRECATED_MSG, RemovedInDjango50Warning)
  
  t/unit/test_schedulers.py:156
    /home/runner/work/django-celery-beat/django-celery-beat/t/unit/test_schedulers.py:156: PytestUnknownMarkWarning: Unknown pytest.mark.celery - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
      @pytest.mark.celery(timezone='Europe/Berlin')
  
  t/unit/test_schedulers.py:188
    /home/runner/work/django-celery-beat/django-celery-beat/t/unit/test_schedulers.py:188: PytestUnknownMarkWarning: Unknown pytest.mark.celery - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
      @pytest.mark.celery(timezone='Europe/Berlin')
  
  t/unit/test_schedulers.py:224
    /home/runner/work/django-celery-beat/django-celery-beat/t/unit/test_schedulers.py:224: PytestUnknownMarkWarning: Unknown pytest.mark.celery - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
      @pytest.mark.celery(timezone='America/New_York')
  
  -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
  =========================== short test summary info ============================
  FAILED t/unit/test_schedulers.py::test_modeladmin_PeriodicTaskAdmin::test_run_task
  !!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
  ============= 1 failed, 55 passed, 4 warnings in 82.00s (0:01:21) ==============

**Comment by auvipy** [comment]
done with https://github.com/celery/django-celery-beat/releases/tag/v2.3.0

**Comment by onny** [comment]
Still hitting this issue while trying to package this module on NixOS :(

**Comment by auvipy** [comment]
can you share more detail?
