### ISSUE TITLE
Descriptors on the latest docs page for the fields clocked, interval, crontab, and solar, appear incorrect

### ISSUE THREAD

**Issue by BenQuigley** [celery/django-celery-beat#546]
### Summary:

The descriptions of the fields `clocked`, `interval`, `crontab`, and `solar` on [the readthedocs page](https://django-celery-beat.readthedocs.io/en/latest/reference/django-celery-beat.models.html#django_celery_beat.models.PeriodicTask) for this package all display the same text:

> ### [crontab](https://django-celery-beat.readthedocs.io/en/latest/reference/django-celery-beat.models.html#django_celery_beat.models.PeriodicTask.crontab)
> Accessor to the related object on the forward side of a many-to-one or one-to-one (via ForwardOneToOneDescriptor subclass) relation.
> 
> In the example:
> 
> ```
> class Child(Model):
>     parent = ForeignKey(Parent, related_name='children')
> ```
> 
> Child.parent is a ForwardManyToOneDescriptor instance.
> 

* Celery Version: n/a
* Celery-Beat Version: latest, 2.2.1

I think those fields represent the four ways of defining when a PeriodicTask should run, and the foreign-key-related description here must be showing up in error, unless I'm seriously misunderstanding how this library works :)

**Comment by auvipy** [comment]
can you be more specific on what seems to be a problem to you?
