### ISSUE TITLE
django admin can not use zh-Hans locale

### ISSUE THREAD

**Issue by wlccgp3** [celery/django-celery-beat#548]
### Summary: django admin can not use zh-Hans locale

* Celery Version: 5.1.2
* Celery-Beat Version: 2.2.1

### Detailed information

my settings is `LANGUAGE_CODE = 'zh-hans'`

django to_locale LANGUAGE_CODE to zh_Hans, but project use zh_hans

**Comment by alirezapla** [comment]
hi 
i think this problem depends on your django version
