### ISSUE TITLE
Solar Schedules break Celery Beat.

### ISSUE THREAD

**Issue by DDevine** [celery/django-celery-beat#55]
I have the latest django-celery-beat (f014edcb954c707cb7628f4416257b6a58689523 not from PyPI) and Celery 4.0.2 and Solar Schedules crash `celery beat` with:
> ...
> [2017-06-22 14:41:17,762: WARNING/MainProcess] File "/opt/myapp-env/lib/python3.5/site-packages/django_celery_beat/schedulers.py", line 102, in is_due
> [2017-06-22 14:41:17,762: WARNING/MainProcess] return self.schedule.is_due(self.last_run_at)
> [2017-06-22 14:41:17,762: WARNING/MainProcess] AttributeError
> [2017-06-22 14:41:17,762: WARNING/MainProcess] :
> [2017-06-22 14:41:17,762: WARNING/MainProcess] 'NoneType' object has no attribute 'is_due'

Using PDB shows that self.schedule is None even though it is certainly making it out the the database because self.model.solar is <SolarSchedule: solar_noon (-20.0, 150.0).

Digging through I found that django_celery_beat.models.PeriodicTask.schedule() does not return the solar schedule. So I addded it like this:

>     @property
>     def schedule(self):
>         if self.interval:
>             return self.interval.schedule
>         if self.crontab:
>             return self.crontab.schedule
>         if self.solar:
>             return self.solar.schedule

After hacking this in I found that 'ephem' was not installed as a dependency of celery or django-celery-beat.  Then I ran into a bug in celery.schedules.solar.remaining_estimate() - after hacking this, `celery beat` no-longer crashed.

**Comment by mheppner** [comment]
I don't think `ephem` is installed by default since it's an optional package to Celery core, similar to `memcache` or `cassandra`.

Your fix looks correct, so just submit a pull request for it.

**Comment by ShaheedHaque** [comment]
I believe this issue can be closed, as the fix is in #56.
