### ISSUE TITLE
v2.2.1 lack 'periodic_task_name'

### ISSUE THREAD

**Issue by caoqianming** [celery/django-celery-beat#550]
### Summary:

Include a *brief* description of the problem here, and fill out the version info below.  

* Celery Version: 5.2.3
* Celery-Beat Version: 2.2.1

### Detailed information

I install beat by pip but found in schedulers.py lack something as fllows:
self.options['periodic_task_name'] = model.name
so cannot get periodic_task_name with django-celery-results in django admin

**Comment by lvelvee** [comment]
`periodic_task_name` was introduced after 2.2.1. We need to wait for a new version release.

**Comment by caoqianming** [comment]
> 

ok.thanks
