### ISSUE TITLE
Cronjob to run every n years and n weeks

### ISSUE THREAD

**Issue by snehlata08** [celery/django-celery-beat#552]
### Summary:

I want to create a reminder very similar to google calendar custom reminder feature. Where user can select number of days/weeks/months/years using djano-celery periodic task and crontab. For eg I want a task to run on every 24th May in every 2 years what can be the expression. After research I found the below expression but it is not working.

`58 10 26 5/24 * `
For this i am getting the below result in crontab generator

![image](https://user-images.githubusercontent.com/79985986/171794160-b1020503-ae80-4907-8c34-917e522f9f2c.png)

Similarly I want a task to run on every Thursday and Friday which repeats in every 2 weeks. As per my research it should be like
`30 10 */14 * 4,5 `

![image](https://user-images.githubusercontent.com/79985986/171794207-25af225b-9b1e-42a7-865a-3e73a3263eb2.png)

Both the above crontabs gets created but they never run. 

* Celery Version: 4.4.6
* Celery-Beat Version: 2.1.0

**Comment by auvipy** [comment]
you reported with an unsupported version of celery. try celery masters with latest release of this package & report again.

**Comment by snehlata08** [comment]
> you reported with an unsupported version of celery. try celery masters with latest release of this package & report again.

@auvipy I updated the celery version but still facing the same problem. 

I have updated to the latest form pypi
celery==5.2.7
kombu==5.2.4
django-celery-beat==2.3.0
pytz==2021.3
redis==3.5.3

Let me know what else needs to be done to make this work.

**Comment by auvipy** [comment]
wait can you try this https://github.com/celery/celery/commit/7fd63f531f0406bdbf6abd3bb0e3714d854f72d2

**Comment by snehlata08** [comment]
@auvipy  Sorry but this didn't work as well for me. Is there something else that needs to be done.

**Comment by auvipy** [comment]
can you provide any failing testcase?

**Comment by snehlata08** [comment]
@auvipy  I want to create cronjob for a task which runs every 2 weeks on Monday and Wednesday at 10.30 am. For that I have created cronjob like this `30 10 */14 * 1,3`

Since 7 days = 1 week i have done 7*2 for the number of days it should repeat because if a task is suppose  to be repeated every 3 days we divide the day of month by that number. 

Similarly there is another task that needs to be performed every 3 years on 17th June at 10.30 am. For this as well i have done 12*3 to get the the number of months. The cron expression that i have created for this is `30 10 17 6/36 *`
Can you tell me the above expressions are right or wrong and if wrong then how they are suppose to be created.

**Comment by snehlata08** [comment]
@auvipy Any update on this issue. Its a very critical and urgent requirement. Any help would be really appreciable.
