### ISSUE TITLE
Period Task Name is blank in django-celery-results

### ISSUE THREAD

**Issue by narc0z** [celery/django-celery-beat#556]
### Summary: Period Task Name is blank in django-celery-results

Include a *brief* description of the problem here, and fill out the version info below.  

* Celery Version:  5.2.6 (dawn-chorus)
* Celery-Beat Version:  2.3.0
* Celery-Results Version: 2.3.1
* Django version: 4.0.3
* Python Version: 3.9

### Exact steps to reproduce the issue:
1. Any periodic task that is executed via celery beat shows up in celery results, but the periodic task name column is blank "-".
2. This is verified from the django admin with the default celery.backend_cleanup, I have also seen this behavior with other beat tasks.

![image](https://user-images.githubusercontent.com/13285233/172427180-297a3c64-ea1b-414b-903a-34fb30b0ef76.png)

![image](https://user-images.githubusercontent.com/13285233/172427340-c8570773-b26d-4b3b-95b2-9d2ea68a4d05.png)

**Comment by auvipy** [comment]
is this a beat issue or result back end?

**Comment by felixmeziere** [comment]
I have the same issue! All my periodic task names are now blank!
<img width="847" alt="image" src="https://user-images.githubusercontent.com/11617630/178465983-db20abf0-9a9b-47b2-8ba5-12b7b87c790c.png">

**Comment by caoqianming** [comment]
I have same question. Task name and Periodic Task name all blank. I don't know what happend

**Comment by caoqianming** [comment]
> ### Summary: Period Task Name is blank in django-celery-results
> Include a _brief_ description of the problem here, and fill out the version info below.
> 
> * Celery Version:  5.2.6 (dawn-chorus)
> * Celery-Beat Version:  2.3.0
> * Celery-Results Version: 2.3.1
> * Django version: 4.0.3
> * Python Version: 3.9
> 
> ### Exact steps to reproduce the issue:
> 1. Any periodic task that is executed via celery beat shows up in celery results, but the periodic task name column is blank "-".
> 2. This is verified from the django admin with the default celery.backend_cleanup, I have also seen this behavior with other beat tasks.
> 
> ![image](https://user-images.githubusercontent.com/13285233/172427180-297a3c64-ea1b-414b-903a-34fb30b0ef76.png)
> 
> ![image](https://user-images.githubusercontent.com/13285233/172427340-c8570773-b26d-4b3b-95b2-9d2ea68a4d05.png)

I rollback django-celery-results from 2.4.0 to 2.3.0 and django-celery-beat is 2.3.0 , everything is ok

**Comment by auvipy** [comment]
https://github.com/celery/django-celery-results/issues/326#issuecomment-1181580646 should help resolve this
