### ISSUE TITLE
ExtendedQuerySet.update_or_create violates signature of parent method

### ISSUE THREAD

**Issue by lociii** [celery/django-celery-beat#562]
### Summary:

`ExtendedQuerySet.update_or_create` violates signature of parent method and `ExtendedQuerySet`s functionality is part of Django since years anyways.

* Celery Version: 
* Celery-Beat Version: 

### Exact steps to reproduce the issue:
1. Call PeriodicTask.objects.update_or_create
2. Expect the same signature as with all other QuerySets
3. Fail

### Detailed information

`ExtendedQuerySet.update_or_create` extends from Django's default `django.db.models.query.QuerySet` but changes the signature of the method. 
See https://github.com/django/django/blob/608ab043f75f1f9c094de57d2fd678f522bb8243/django/db/models/query.py#L949 the parent method returns a tuple of `object, created: bool` whereas the derived one only returns the `object` and there's no way to figure out if the task has been changed or not.

tbh I don't know if this is a chicken/egg problem. `update_or_create` was introduced to Django in 1.7 on 2014/09/02 and the initial commit to `django-celery-beat` was on 2016/08/04 but named `initial import` so there might have been some code before that.

Imho the signature should be aligned with the parent method or `ExtendedQuerySet` should be completely removed as Django provides the same functionality now for years.

Let me know what you prefer and I'd be more than happy to open a pull request.

**Comment by auvipy** [comment]
codes of this package dates back https://github.com/celery/django-celery/commits/master?after=2b35a2eb8545d2cd7d90c69af4bb2f6aa51a436a+34&branch=master&path%5B%5D=djcelery&path%5B%5D=managers.py&qualified_name=refs%2Fheads%2Fmaster later the packages were split

**Comment by auvipy** [comment]
you are welcome with a PR
