### ISSUE TITLE
Add support for Django 4.1

### ISSUE THREAD

**Issue by carlosdorneles-mb** [celery/django-celery-beat#566]
First, Thanks for this great project! 👍

Summary:
Current django-celery-beat requires Django (>=3.2.13,<4.1) and hence doesn't install together w/ [Django 4.1.](https://docs.djangoproject.com/en/4.1/releases/4.1/)

**Comment by auvipy** [comment]
will relax the requirement and try to push a new release

**Comment by awemulya** [comment]
+1

**Comment by Olerdrive** [comment]
Any updates?

**Comment by auvipy** [comment]
work in progress https://github.com/celery/django-celery-beat/pull/567

**Comment by Crocmagnon** [comment]
Is there still something holding django-celery-beat from supporting Django 4.1?

**Comment by goatwu1993** [comment]
Django 4.1 support is merged into the master branch at #567 
I believe the only thing left is a new release.

**Comment by rbarsegi** [comment]
Please merge #589 to allow support for Django 4.1

**Comment by carlosdorneles-mb** [comment]
@rbarsegi PR #589 is not needed as PR #567 is already merged and it supports Django 4.1. We are just waiting for the generation of a new version of the code that is in the master.

**Comment by goatwu1993** [comment]
https://github.com/celery/django-celery-beat/pull/581#issuecomment-1276569087

**Comment by auvipy** [comment]
yeah going to

**Comment by utapyngo** [comment]
> yeah going to

What is the estimate release date?

**Comment by auvipy** [comment]
released https://github.com/celery/django-celery-beat/releases/tag/v2.4.0 please try and report bugs

**Comment by JamesonNetworks** [comment]
> released https://github.com/celery/django-celery-beat/releases/tag/v2.4.0 please try and report bugs

Thanks for all that you all do! We appreciate ya!
