### ISSUE TITLE
Signals can not connect to `OneToOneField`.

### ISSUE THREAD

**Issue by 954-Ivory** [celery/django-celery-beat#572]
Because django let `sender = self.__class__`:
https://github.com/django/django/blob/e9fd2b572410b1236da0d3d0933014138d89f44e/django/db/models/base.py#L860

If you inheritance from `PeriodicTask`(same as `OneToOneField`), and overwrite `save()` in your field, like this:

``` python3
class YourPeriodicTask(PeriodicTask):
    # ...
    def save(self, *args, **kwargs):
        # ...
        super().save(*args, **kwargs)
```

The `pre_save.sender` will be `YourPeriodicTask`, not `PeriodicTask`.
So, the signal will not be receive.

**Comment by auvipy** [comment]
is it bug or what you are suggesting?

**Comment by 954-Ivory** [comment]
> is it bug or what you are suggesting?

Yeah, I think it's a bug.
The PR comming soon~
