### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by caduri** [celery/django-celery-beat#59]
Hi, There are a lot of new commits since November 2016
can you please release a new version?

Thanks!

**Comment by caduri** [comment]
Hi @ask, can you please address this issue

**Comment by DDevine** [comment]
I have some fixes relating to solar scheduling that would be good to pull in first, but a new release is very high on my wish-list.

**Comment by mheppner** [comment]
From what I saw at celery/celery, it looks like the team doesn't have release access.

**Comment by auvipy** [comment]
Hi I have started working full time for celery. so you will see things are changing quick :)

**Comment by mheppner** [comment]
Great news, thanks! Let me know if you need assistance with either of the Django apps. I've been trying to help out on the mailing list too.

**Comment by auvipy** [comment]
great to hear that :)

**Comment by caduri** [comment]
@auvipy great to hear! Waiting for your first release ;)

**Comment by auvipy** [comment]
I will triage, review and code. for now @thedrow is the release manager

**Comment by eskhool** [comment]
@thedrow , @auvipy ...1 year since the last release in a work in progress product like django celery beat is a long time. Would it be that hard to request atleast a 1.0.2 instead of everybody having to keep up with master. Thanks

**Comment by thedrow** [comment]
@eskhool I'll add it to my TODO list.

**Comment by thedrow** [comment]
Done. Apologies for the delay :)
