### ISSUE TITLE
Use prefetch_related in DatabaseScheduler.all_as_schedule 

### ISSUE THREAD

**Issue by jahazieldom** [celery/django-celery-beat#608]
### Summary:

We use django-celery-beat in a multi-tenant application, we have 20K rows of periodic tasks (each tenant has its own periodic tasks), but when any task is created, updated or deleted the method `DatabaseScheduler.all_as_schedule` it takes a long time to be processed, i think you could use `self.Model.objects.enabled().prefetch_related("interval", "crontab", "solar", "clocked")` and with that it significantly reduces the processing time. 

### Versions
celery==5.2.7
django-celery-beat==2.4.0

**Comment by auvipy** [comment]
I thinkk we should consider this for all the models that will be benefited from prefetch_related
