### ISSUE TITLE
crontab does not use the CELERY_TIME_ZONE correctly

### ISSUE THREAD

**Issue by eskhool** [celery/django-celery-beat#63]
Although the CELERY_TIME_ZONE is used to display the last_run_time, the actual run time is the time stored in the database converted to UTC instead of being the time in the local time zone.

The machine time zone is set to the local time zone already if that matters

**Comment by DDevine** [comment]
There is some funky stuff (some things might be bugs, some are just undocumented/confusing) regarding timezones - see https://github.com/celery/django-celery-beat/issues/57

The time zone used in the database probably should be UTC, though it needs to be converted on the way out of the database to either Django TIMEZONE or CELERY_TIMEZONE. It's not exactly straight forward and multiple use-cases need to be considered before deciding that the behaviour is a bug or not.

**Comment by auvipy** [comment]
> regarding timezones - see #57

closing as per that.
