### ISSUE TITLE
Tasks don't run if manually not setting last_run_at. 

### ISSUE THREAD

**Issue by pspsdev** [celery/django-celery-beat#637]
### Summary:

Tasks don't run if manually not setting last_run_at. 

* Celery Version: 2.4.0
* Celery-Beat Version: 5.2.7
* Django timezone is unchanged (UTC)

### Exact steps to reproduce the issue:
1. Create a new periodic task leaving last_run_at field empty

If last_run_at is set, task run at a wrong schedule. E.G every 10 seconds, run at exactly every 3 minutes.

**Comment by gg-mmill** [comment]
Hello, I am facing a similar issue (PeriodicTask not starting until `last_run_at` has been set. Did you find why this happened ? 

Not noticing any issue with wrong scheduling though.
