### ISSUE TITLE
Admin filters

### ISSUE THREAD

**Issue by robvdl** [celery/django-celery-beat#64]
I think the Django celery beat app could do with a bit of admin improvements, the admin pages are quite lacking to be honest:

* Filters would be nice for a starter, how can I quickly filter on SUCCESS/FAILED task results (at the moment I have to do this through sorting)
* Date filter might be useful for people that keep results around for a long time, but maybe not hugely important.
* Maybe searching

**Comment by eskhool** [comment]
@robvdl, we have written our own admin and are over riding the default. I think that may be a good enough way to go since the requirement for admin may vary a lot. Having said that most of what you have suggested is what we have implemented but I wouldn't venture to say the same holds for all :)

**Comment by wardal** [comment]
Made some filters in local repo and pushed to original repo: https://github.com/celery/django-celery-results/pull/30
