### ISSUE TITLE
How did it work out

### ISSUE THREAD

**Issue by nfyn** [celery/django-celery-beat#643]
### Summary:

Include a *brief* description of the problem here, and fill out the version info below.  

* Celery Version: 
* Celery-Beat Version: 

### Exact steps to reproduce the issue:
1. 
2. 
3. 

### Detailed information

Please include more detailed information here, such as relevant information about your system setup, things you did to try and debug the problem, log messages, etc.

**Comment by auvipy** [comment]
don't open useless issues. open discussion for any query first. also stackoverflow is a great first option
