### ISSUE TITLE
ScheduledTask new feature request

### ISSUE THREAD

**Issue by marco-silva0000** [celery/django-celery-beat#66]
I think it would be nice new feature to have a Class that can be scheduled like a PeriodicTask, but with a automatic "delete" after that run.

Currently i use Periodic tasks with crontabs to schedule events, and i must "manualy" cleanup the created tasks to ensure that next year the same task wont run again.

Imagine the use case of a one time future reminder event to send an email, we want to remind that time only and not again the next year.

If there is a better way to do this please teach me :)

**Comment by eskhool** [comment]
@marco-silva0000, a better generalisation would be adding an option of number of recurrences or a last execution date/time or both. This way if somebody wants to run a reminder 3 times before giving up it can be accommodated. Agreed?

**Comment by marco-silva0000** [comment]
yes, that may be a better aproach if easer to implement. I don't know if It would mess up a lot of hidden magic, or add overhead on some of the tradicional use cases, but someone more familiar with the core may have an insight of what would be the best aproach.
this behaviour could be extended, like make a reminder at monday 9:00AM and repeat every hour 3 times or untill dismissed, etc.
My use case is not reminder related, so I'll leave it here as well. I just use a PeriodicTask with a crontab object to schedule each irrigation on a farm.

**Comment by auvipy** [comment]
hey guys, what's your thoughts on this issue with the latest PyPI release?

**Comment by auvipy** [comment]
if you feel still the same just pingme.
