### ISSUE TITLE
Release Django 5.0 compatible package to PyPI

### ISSUE THREAD

**Issue by nijel** [celery/django-celery-beat#680]
### Summary:

Include a *brief* description of the problem here, and fill out the version info below.  

* Celery Version: 5.3.5
* Celery-Beat Version: 2.5.0

### Exact steps to reproduce the issue:
1. Try to install Django 5.0a1 with django-celery-beat
2. `django-celery-beat 2.5.0 has requirement Django<5.0,>=2.2, but you have django 5.0a1.`

### Detailed information

See https://docs.djangoproject.com/en/dev/releases/5.0/ for release notes.

**Comment by auvipy** [comment]
https://github.com/celery/django-celery-beat/pull/681

**Comment by yanivtoledano** [comment]
@auvipy - is there a timeline for the next release (with 5.0 support)?

**Comment by auvipy** [comment]
Hopefully early next week.

**Comment by kozlek** [comment]
Hi 👋

Based on what I understood, Django 5.0 support was simply a matter of relaxing the dependency constraints.
I'm not challenging the fact we have a dependency constraint with an upper bound.

The patch was made on the Sep 19, which is the release date of the first Django 5.0 alpha. This is an achievement: we managed to add support for the new Django release very early in the development process 🥳

However, 2 months later and 4 days after the final Django release, users are still not able to use it (or even test it easily) because we failed to release the working code we produced 2 months ago 😕

Far from judging (I've done manual releases myself for some time so I know how time consuming it is 😉), what can we do to help you @auvipy to ease the release process of this version and the following ones? 

I'll be happy to look into a CI pipeline to provide an automated release if you are okay for it, but if you prefer to do it manually tell us if you need new maintainers for reviewing PRs or doing issues triage 🙂

**Comment by cclauss** [comment]
% `python3.12 -m venv .venv`
% `source .venv/bin/activate`
% `pip install --upgrade pip`
% `pip install django==5.0 django-celery-beat==2.5.0` --> **_Failure_**
% `pip install django==5.0 django-celery-beat` --> Success but with `django-celery-beat` downgraded to v2.1.0 and `django-timezone-field` downgraded from `v6.1.0` to `v4.2.3`

Please release a new version to PyPI.

**Comment by cclauss** [comment]
Were you able to get the tests to pass on Py3.12 and Dj5.0?

**Comment by kozlek** [comment]
Launching `tox` with the latest commit of the master branch using `tox -e py312` installs Django 5.0 and reports 1 failure.

I choose to ignore it because it's related to the removal of `django.utils.timezone.utc` alias and it only affects systems running with `USE_TZ=False` which is not my case.

**Comment by kozlek** [comment]
It's quite easy to fix, as we simply need to use `datetime.timezone.utc` [here](https://github.com/celery/django-celery-beat/blob/main/django_celery_beat/utils.py#L20) instead, as we already do [here](https://github.com/celery/django-celery-beat/blob/main/django_celery_beat/tzcrontab.py#L15).

However, we might also want to fix in the same time warnings regarding the deprecation of `datetime.utcnow()`, as I did for `djangorestframework-simplejwt`: https://github.com/jazzband/djangorestframework-simplejwt/pull/765

IMHO, we should simply get rid of old python / django versions, remove support for `USE_TZ=False` and native datetime.
It would simplify library code a lot and it seems to be the direction taken by both [Django](https://docs.djangoproject.com/en/5.0/releases/5.0/#features-removed-in-5-0) and [Python](https://docs.python.org/3/whatsnew/3.12.html#deprecated).

**Comment by cclauss** [comment]
* #703

**Comment by chirag-jn** [comment]
Is there an ETA for django 5 support? I see that there's work in progress but I am eagerly waiting for the release.

**Comment by cclauss** [comment]
If you or others are looking for ways to help move things forward, please see https://github.com/celery/celery/issues/8748 in the main Celery project.

**Comment by chirag-jn** [comment]
I believe that the celery project has removed references to datetime.utcnow so we can proceed with the release of django-celery-beat for django 5.0

**Comment by cclauss** [comment]
@nijel Please consider changing the title of this issue to `Django 5.0 release to PyPI` since I believe that is the only step that is still required.

Others, If you want to provide maintainers more confidence to make this release then please consider installing the `main` branch with `pip install https://github.com/celery/django-celery-beat.git` and then run your tests and exercise the Celery pieces of your Django app(s).  If you see problems, please comment here.  I did this and saw no problems on localhost and our staging server.

**Comment by heckad** [comment]
Can you please release at least a release candidate? Otherwise, testing without hashes is somehow not very good in modern world.

**Comment by cclauss** [comment]
You don't trust GitHub?  ;-)

**Comment by heckad** [comment]
We have a command in ci to install from `pip` with the `--require-hashes` flag. If you just add a link to git there will be an error. Have you really never used the `--require-hashes` flag in your life and did not understand what hashes we are talking about?

**Comment by heckad** [comment]
Doesn't work

```
# pip install -r requirements.txt --require-hashes                                                                                                                                                                                                  
Collecting django-celery-beat@ git+https://github.com/celery/django-celery-beat@f66796b9c5c9e47d118cb5b41d970f07cce72bbe (from -r requirements.txt (line 1))
ERROR: Can't verify hashes for these requirements because we don't have a way to hash version control repositories:
    django-celery-beat@ git+https://github.com/celery/django-celery-beat@f66796b9c5c9e47d118cb5b41d970f07cce72bbe from git+https://github.com/celery/django-celery-beat@f66796b9c5c9e47d118cb5b41d970f07cce72bbe (from -r requirements.txt (line 1))
```

**Comment by cclauss** [comment]
@heckad
* https://github.com/pypa/pip/issues/6469

**Comment by DrJfrost** [comment]
any news about the release to the pipy package? I think there is way too much focus on django 5.1 without proper implementation for django 5 support

**Comment by csulit** [comment]
Any news regarding the upgrade? :)

**Comment by Couapy** [comment]
Hello :wave: 
Any updates ? Still blocked on the subject

**Comment by cclauss** [comment]
@csulit @Couapy https://github.com/celery/django-celery-beat/issues/680#issuecomment-1891665075
* https://github.com/celery/django-celery-beat/issues/698#issuecomment-1904043244

**Comment by amweiss** [comment]
What else needs to happen here other than tag the version and push it to pypi?

**Comment by cclauss** [comment]
@amweiss https://github.com/celery/django-celery-beat/issues/680#issuecomment-1891665075

**Comment by amweiss** [comment]
@cclauss yes, I guess I'm wondering what else needs to happen before a maintainer tags and releases as we have all been using it from the git repo for a while now without issues. If there's some further evidence needed I'm happy to supply it. We have been running against the git version for about 4 weeks now without issue.

**Comment by deronnax** [comment]
Can I suggest to give up upper bound constraints?

It's considered a pretty negative practice, see [this article on the subject](https://iscinumpy.dev/post/bound-version-constraints/#tldr) and [Poetry's FAQ](https://iscinumpy.dev/post/bound-version-constraints/#tldr).
It hit us in our migration to Django 5, preventing to upgrading django without cheating the package manager, whereas as for 99% of upper version constrained packages, it works actually just fine with the unduly forbidden upper version.

Upper-bound constraints should be solely reserved for the very rare case where you tried with the new version and you *know* it doesn't work.

**Comment by ddahan** [comment]
@deronnax thanks!
PS: the second link should be [this one](https://python-poetry.org/docs/faq/#are-unbound-version-constraints-a-bad-idea) I guess

**Comment by deronnax** [comment]
Oops, yes indeed. Thank you so much.

**Comment by cclauss** [comment]
The euphemism `upper-bound constraints` should be replaced with the traditional name — a software release process.

Why deprive the maintainers of this project the alpha, beta, production release that Linux, macOS, Windows, Python, Django, and even Poetry all have?  This software operates in complex combinations with other systems and is used to process mission-critical data.

If maintainers are prohibited testing/repairing before production use then they need software quality rumors/concerns and respond to complex issues opened by unhappy users.

Just ask yourself why Poetry releases with alpha, beta and production releases but encourages others not to follow their own example.

**Comment by FluxZA** [comment]
https://github.com/celery/django-celery-beat/issues/680#issuecomment-1891665075 with regard to this issue, we have upgraded as suggested and are experiencing no issues on Django 5.

**Comment by deronnax** [comment]
@cclauss I think you are confusing two different subjects. I don't see why you oppose relax-bound constraints for libraries and a software release process. A ton (actually most) of python library do have a release process and have no upper-bound constraints ; Django being the first of them (see its [setup.cfg dependencies list](https://github.com/django/django/blob/main/setup.cfg#L36-L43)). As for Poetry, they are not a library, they are an app. An application is the total final chain link of its dependency chain, so an app can do whatever it wants on the expression of its dependency. 99% of the time, they are all pinned to the exact version. That's what Poetry does, you can see it because they have a poetry.lock.

**Comment by nlsfnr** [comment]
Building on @deronnax's points, I want to emphasize the option for downstream applications to lock their dependency versions (e.g., django==4.2) at their discretion.

This decision should, in my opinion, _not_ be made by upstream library authors, especially if there is no concrete reason / evidence to believe that newer versions of the library's dependencies will break the library. This is especially true for frameworks or libraries, such as Django, that have a disproportionate impact on downstream code bases where unnecessary version locking can cause headaches.

**Comment by Scalamoosh** [comment]
> [#680 (comment)](https://github.com/celery/django-celery-beat/issues/680#issuecomment-1891665075) with regard to this issue, we have upgraded as suggested and are experiencing no issues on Django 5.

I'd like to also confirm that I have been running a fairly large project (with its fair share of celery-related quirks) with the recent changes (Pinned at `acd10a390c85414a59e9b37be6226e4a9ea4fb81`) with no issues.

**Comment by auvipy** [comment]
I would like to revisit this issue very soon.

**Comment by cclauss** [comment]
> there is no concrete reason / evidence to believe that newer versions of the library's dependencies will break the library.

Please review the eight pull requests above.  For instance... `utils.make_aware()` will crash on Dj5 without https://github.com/celery/django-celery-beat/pull/703#issue-2048947641

**Comment by csulit** [comment]
The only issue with my setup now is that the task is not registered on the Django admin. However, it works if I register the task via a custom **property.**

![image](https://github.com/celery/django-celery-beat/assets/31933946/bebf9a6c-bbef-4bdf-b059-f532472325ef)

requirements.txt

![image](https://github.com/celery/django-celery-beat/assets/31933946/3afcab57-5092-4738-bf4a-36d0b9fd618e)

**Comment by sandeepbol** [comment]
When can we expect a release? Any ETAs?

**Comment by Nusnus** [comment]
> When can we expect a release? Any ETAs?

Are we ready for a release? @cclauss

**Comment by cclauss** [comment]
Yes.  Please look at #737 and then let's release!

**Comment by osuthorpe** [comment]
Was this released?

**Comment by cclauss** [comment]
> Was this released?

# YES... https://pypi.org/project/django-celery-beat is v2.6.0
