### ISSUE TITLE
Minor documentation error

### ISSUE THREAD

**Issue by schwobaseggl** [celery/django-celery-beat#693]
### Summary:
In the `README` it states that the crontab `30 * * * *` corresponds to  *"execute every 30 minutes"*.

### Detailed information
This is, of course, wrong. It means *"execute at minute 30 of every hour"*.

**Comment by cclauss** [comment]
Agreed:
* [`https://crontab.guru/#30_*_*_*_*`](https://crontab.guru/#30_*_*_*_*) is __At minute 30.__ (every hour, every day, every month)
* [`https://crontab.guru/#*/30_*_*_*_*`](https://crontab.guru/#*/30_*_*_*_*) is __Every 30th minutes.__
