### ISSUE TITLE
django 5.0

### ISSUE THREAD

**Issue by qengine13** [celery/django-celery-beat#698]
Installed django 5.0. and got the warning that celery beat 2.5.0 not compatible... Will there be an update?

**Comment by aminvsf** [comment]
I was wondering the same thing. It's the only package among my other dependencies which is incompatible.

**Comment by piotr-grzelka** [comment]
#681

**Comment by tuky** [comment]
So it only needs a new release? Considering how simple the patch was, I would suggest to loosen the deps a little bit and at least support Django < 6 and not only Django < 5.1. Nobody can tell the future, but IMO package maintainers should focus on the minimum dependency versions and packages users on maximum dependency versions.

**Comment by cclauss** [comment]
% `python3.12 -m venv .venv`
% `source .venv/bin/activate`
% `pip install --upgrade pip`
% `pip install django==5.0 django-celery-beat==2.5.0` --> **_Failure_**
% `pip install django==5.0 django-celery-beat` --> Success but with `django-celery-beat` downgraded to v2.1.0 and `django-timezone-field` downgraded from `v6.1.0` to `v4.2.3`

Please release a new version to PyPI.

**Comment by hansegucker** [comment]
A release would be very great to bring forward our own release.

**Comment by tuky** [comment]
Of course, we're all free to (temporarily) exclude this package from our requirements locking pipeline and install our deps something like this:

```sh
.../pipenv install --system --deploy
.../pip install python-crontab>=2.3.4 cron-descriptor>=1.2.32
.../pip install django-celery-beat==2.5.0 --no-dependencies
```

**Comment by JulianTenschert** [comment]
> % `python3.12 -m venv .venv` % `source .venv/bin/activate` % `pip install --upgrade pip` % `pip install django==5.0 django-celery-beat==2.5.0` --> **_Failure_** % `pip install django==5.0 django-celery-beat` --> Success but with
> 
> * `django-celery-beat` downgraded `2.5.0` --> `v2.1.0` and
> * `django-timezone-field` downgraded from `v6.1.0`--> `v4.2.3`
> 
> Please release a new version to PyPI.

Thanks, this is a good workaround.

**Comment by cclauss** [comment]
The tests pass on CPython and Django v5 but they fail on PyPy3.10 and Django v5.  Help needed.
 * https://github.com/celery/django-celery-beat/pull/705

Running on old versions of `django-celery-beat` and `django-timezone-field` is probably not a good idea.

**Comment by ddoroshev** [comment]
> This repo's tests pass on CPython and Django v5 but they fail on PyPy3.10 and Django v5. Help needed.

Done #708. Long story short: a bug in PyPy 3.10-7.3.13.

**Comment by esauser** [comment]
When can we expect a new release?

**Comment by Nigel2392** [comment]
Am I seeing this right, is Django 5.1 not going to be supported in the upcoming release?

**Comment by cclauss** [comment]
https://github.com/celery/django-celery-beat/pulls?q=is%3Apr+author%3Acclauss+is%3Aclosed fixed the timzone issues that I could find and Py5.0 tests https://github.com/celery/django-celery-beat/blob/main/tox.ini#L15 pass at https://github.com/celery/django-celery-beat/actions/workflows/test.yml

Let's focus on getting a [release on PyPI](https://pypi.org/project/django-celery-beat/) that supports Django v5.0 (shipping) before we focus too much on Django 5.1 (NOT shipping).

**Comment by amweiss** [comment]
Any news here? The issue was closed, but no release was made.

**Comment by Nigel2392** [comment]
> Any news here? The issue was closed, but no release was made.

There was a release made, it got deleted.
Perhaps they caught a bug.

**Comment by amweiss** [comment]
> There was a release made, it got deleted. Perhaps they caught a bug.
> 
> _edit_ [#680 (comment)](https://github.com/celery/django-celery-beat/issues/680#issuecomment-1890462742)

The Django 5 tests passed in this package, so I'm not sure if that's related. But per the comment, I made a PR to resolve the base celery deprecation warnings: https://github.com/celery/celery/pull/8791

**Comment by ddahan** [comment]
Please stop posting "any news ?" messages many times. At least 3 reasons to NOT do this:

- The maintainers are totally aware there is a release to do, so if they don't do it, they have a reason. Pushing them does not help, and is not respectful.
- You decided to upgrade to Django 5.0 without being forced to. Being an early adopter means lots of packages are not compatible at day one, so please consider downgrade or think carefully next time before upgrading.
- It sends an email to lots of people (and yes, sorry for doing the same because of this message).

**Comment by ribeaud** [comment]
> Please stop posting "any news ?" messages many times. At least 3 reasons to NOT do this:
> 
> * The maintainers are totally aware there is a release to do, so if they don't do it, they have a reason. Pushing them does not help, and is not respectful.
> * You decided to upgrade to Django 5.0 without being forced to. Being an early adopter means lots of packages are not compatible at day one, so please consider downgrade or think carefully next time before upgrading.
> * It sends an email to lots of people (and yes, sorry for doing the same because of this message).

I do not think anything more than this statement was needed (at least for me). I did not see here any clear post about a release happening soonish, or not so soonish. Thanks a lot for the quick answer. Very appreciated. And oops soory, I did it again (disturbing a lot of people...).

**Comment by adampl** [comment]
> You decided to upgrade to Django 5.0 without being forced to. Being an early adopter means lots of packages are not compatible at day one

Personally I don't care about Django version, I'm just waiting for the bugfixes. Delaying the release by months just because of Django means that there's something wrong with the release plan...
When nobody provides any ETA, you shouldn't be surprised that people will keep asking. If you want to release some of the pressure, consider releasing a 2.5.x patch version with the long overdue bugfixes.

**Comment by trAve3113r** [comment]
People shouldn't make such strong demands for an open source project run by people who volunteer their time. If it's a paid subscription, yeah... you're free to demand value for money.

**Comment by cclauss** [comment]
This issue is closed and should be **_locked_** by a maintainer.  Discussion should move to #680 which has a title that describes what is still left to do. 
* #680
* https://pypi.org/project/django-celery-beat
