### ISSUE TITLE
Question: Get reference to parent PeriodicTask within Celery task

### ISSUE THREAD

**Issue by philsheard** [celery/django-celery-beat#72]
Hi - a question more than an issue, which I couldn't see documented anywhere.

Is there any known way to get a reference to the PeriodicTask within each scheduled task, eg using Celery's `current_task` method. My use case is that I have Celery tasks running both on a schedule and ad-hoc, so I would like to be able to log the source schedule / originator of each task as it runs.

I've looked through the `beat` codebase to see whether I could fork-and-modify the code at the time of the scheduled task being raised. But couldn't clearly identify where the tasks are actually added to the queue.

Any advice gratefully received, or just pointers to how I can continue to self-help.

**Comment by ShaheedHaque** [comment]
The way I do it is to pass the id of the PeriodicTask in as one of the kwargs. Inside the task, I can then just:
>        schedule = PeriodicTask.objects.get(id=kwargs['schedule'])

**Comment by nick-nz** [comment]
@ShaheedHaque what did you type in the Django admin kwargs to reference the id?

**Comment by prafulbagai708** [comment]
@nick-nz Were you able to find the solution when passed through admin?

**Comment by auvipy** [comment]
do we have anything actionable to be added to this package?
