### ISSUE TITLE
Getting RuntimeWarning with django-celery-beat==2.6.0, django==5.0.3

### ISSUE THREAD

**Issue by stefanofusai** [celery/django-celery-beat#741]
### Summary:

I'm getting a weird warning on my celery beat instance: `[2024-03-07 22:01:57,546: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/django/db/models/fields/__init__.py:1595: RuntimeWarning: DateTimeField PeriodicTask.last_run_at received a naive datetime (2024-03-07 22:00:00.253475) while time zone support is active.`

* Celery Version: 5.3.6
* Celery-Beat Version: 2.6.0
* Django Version: 5.0.3 (I'm pretty sure that this was happening with Django 4.x as well)

### My relevant settings in settings.py
```py
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
CELERY_BEAT_SCHEDULE = {
    "my_task": {
        "task": "project.tasks.my_task",
        "schedule": crontab(minute=0),
    },
}
USE_TZ = True
```

### celery.py
```py
app = Celery("tasks",)
app.config_from_object("django.conf:settings", namespace="CELERY")
app.autodiscover_tasks()
```

Any idea why this is happening? Thank you

**Comment by koleror** [comment]
Hey! I've been hunting this issue for a while now and never found a fix. Have you found any by any chance?

**Comment by cclauss** [comment]
`ruff check --select=DTZ` lint rules will encourage using timezone-aware dates and datetimes.
* https://docs.python.org/3/whatsnew/3.12.html#deprecated Scroll to datetime...
* https://docs.djangoproject.com/en/5.0/releases/5.0/#features-removed-in-5-0
* https://docs.astral.sh/ruff/rules/#flake8-datetimez-dtz

**Comment by stefanofusai** [comment]
@cclauss Thank you for your feedback, I already have that rule enabled. The field that is being generated without a timezone is internal to `django-celery-beat`, it is `PeriodicTask.last_run_at` so I'm not sure what I'm doing wrong/what I'm supposed to do.

**Comment by cclauss** [comment]
Understood.  There are lots of PRs and issues on `last_run_at`...
* https://github.com/search?q=repo%3Acelery%2Fdjango-celery-beat+last_run_at&type=pullrequests

**Comment by cclauss** [comment]
Would it be possible to add a test that fails so we can all see the failure and we can prove any proposed fixes?
* https://github.com/celery/django-celery-beat/tree/main/t/unit

**Comment by stefanofusai** [comment]
Unfortunately I'm unable to reproduce this issue to further debug it, the warning logs are emitted randomly when running celery locally but are emitted at every task execution when in production inside a docker container.
