### ISSUE TITLE
Django check fails on migrate

### ISSUE THREAD

**Issue by WannaFight** [celery/django-celery-beat#767]
### Summary:
Can't install django-celery-beat due to duplicate migrations

* Django Version: 2.2.28
* Celery Version: 5.2.6
* Celery-Beat Version: 2.2.1 

### Exact steps to reproduce the issue:
1. Project with Django 2.2 and installed Celery 5.2
2. `pip install django-celery-beat==2.2.1`
3. add `django_celery_beat` to `INSTALLED_APPS`
4. `manage.py migrate`

And as I see these duplicate migrations are still presented in future version of library 
### Detailed information

```shell
./manage.py check
SystemCheckError: System check identified some issues:

ERRORS:
?: Duplicated names of migrations `django_celery_beat.0006`
        HINT: Remove migration created by you and run `manage.py makemigrations` again

System check identified 1 issue (0 silenced).
```

**Comment by cclauss** [comment]
`HINT: Remove migration created by you and run `manage.py makemigrations` again`

**Comment by WannaFight** [comment]
ah, ok, I see it. Will try to do the same on newer Django later

**Comment by WannaFight** [comment]
@cclauss Hi! Just updated our project to Django 4.2 and still facing same issue. After installing `django_celery_beat` and adding it to `INSTALLED_APPS` Django check fails
 - Django Version: 4.2.14
 - Celery Version: 5.3.1
 - Celery-Beat Version: 2.6.0

```sh
$ pip freeze | grep -E "Django|celery"
celery==5.3.1
Django==4.2.14
django-celery-beat==2.6.0
$ ./manage.py check
SystemCheckError: System check identified some issues:

ERRORS:
?: Duplicated names of migrations `django_celery_beat.0006`
        HINT: Remove migration created by you and run `manage.py makemigrations` again

System check identified 1 issue (0 silenced).
```

**Comment by cclauss** [comment]
So what happens when you:
> Remove migration created by you and run `manage.py makemigrations` again?

**Comment by WannaFight** [comment]
I do not have any unapplied migrations, also Django check is executed before `makemigrations` so it also fails. `showmigrations` with skipped checks is indeed showing multiple migrations with 0006 number
```shell
manage.py showmigrations --skip-checks --plan | grep -v "[X]"
[ ]  django_celery_beat.0001_initial
[ ]  django_celery_beat.0002_auto_20161118_0346
[ ]  django_celery_beat.0003_auto_20161209_0049
[ ]  django_celery_beat.0004_auto_20170221_0000
[ ]  django_celery_beat.0005_add_solarschedule_events_choices
[ ]  django_celery_beat.0006_auto_20180322_0932  <----
[ ]  django_celery_beat.0007_auto_20180521_0826
[ ]  django_celery_beat.0008_auto_20180914_1922
[ ]  django_celery_beat.0006_auto_20180210_1226  <----
[ ]  django_celery_beat.0006_periodictask_priority  <----
[ ]  django_celery_beat.0009_periodictask_headers
[ ]  django_celery_beat.0010_auto_20190429_0326
[ ]  django_celery_beat.0011_auto_20190508_0153
[ ]  django_celery_beat.0012_periodictask_expire_seconds
[ ]  django_celery_beat.0013_auto_20200609_0727
[ ]  django_celery_beat.0014_remove_clockedschedule_enabled
[ ]  django_celery_beat.0015_edit_solarschedule_events_choices
[ ]  django_celery_beat.0016_alter_crontabschedule_timezone
[ ]  django_celery_beat.0017_alter_crontabschedule_month_of_year
[ ]  django_celery_beat.0018_improve_crontab_helptext
```

**Comment by WannaFight** [comment]
oh, actually this check (that raises that exception) is a custom made and I've never come across it in our project... after disabling it everything works fine 

I'm really sorry for inconvenience
