### ISSUE TITLE
New release to PyPI is required for Django v5.1

### ISSUE THREAD

**Issue by cclauss** [celery/django-celery-beat#781]
### Summary:

* #755
* #756
* #761
* https://pypi.org/project/Django is currently v5.1.

Installing django-celery-beat on Django v5.1 will ___downgrade___:
`django-celery-beat`: 2.6.0 --> 2.1.0
`django-timezone-field`: 7.0.0 --> 4.2.3

### Exact steps to reproduce the issue:
1. `pip install Django django-celery-beat`

### Detailed information

This problem has been fixed on the `main` branch of this repo but that code has not been published to PyPI.

**Comment by auvipy** [comment]
I will try to do this this week end saturday / sunday. feel free to ping me on friday night so that I can see it im sonntag

**Comment by cclauss** [comment]
Ping. ;-)  I am attending some live music this evening but after that I will create a #739-like pr if you have not already done so.
* #739

**Comment by cclauss** [comment]
OK.
* [ ] The DRAFT v2.7.0 release is now at https://github.com/celery/django-celery-beat/releases
* [ ] When ready please copy that text to the top of `Changelog`.
* [ ] Ensure that `bumpversion` updates the version in files:
    * [ ] `.bumpversion.cfg`, `README.rst`, `django_celery_beat/__init__.py`, and `docs/includes/introduction.txt`
* [ ] Build and publish via #749

**Comment by cclauss** [comment]
@auvipy please let me know if you have any questions.

**Comment by mrzorn** [comment]
Any updates on when the 2.7.0 release is planned?

**Comment by auvipy** [comment]
> @auvipy please let me know if you have any questions.

you have to take responsibility of this release! and update the release documentation based on current scenario. Due to some gap, I am hesitant. and some personal / professional emergency arise lately.

**Comment by cclauss** [comment]
OK...  Will do.

**Comment by Nusnus** [comment]
> OK...  Will do.

Let me know if you need a hand ✋@cclauss

**Comment by vasilistotskas** [comment]
release on pypi ?

**Comment by Nusnus** [comment]
> release on pypi ?

@cclauss you should be able to release on pypi now

**Comment by cclauss** [comment]
# https://pypi.org/p/django-celery-beat 👍 🎉 🚀 📦
