### ISSUE TITLE
Disabling a periodic task is not working

### ISSUE THREAD

**Issue by rajashekarappala** [celery/django-celery-beat#79]
I have disabled all my periodic tasks by setting enabled = False. But the tasks are still running, I am unable to find what am I doing wrong. Please let me know If I am not doing it properly. Here is the PeriodicTask table screenshot. Thank you.

**Comment by vincejah** [comment]
@rajashekarappala I am having the same issue. Have you found what's going wrong?

**Comment by rajashekarappala** [comment]
Hi @vincejah, Yes it is fixed for me.
` 
task = PeriodicTask.objects.get(id=1)
task.enabled = True
task.save()
`
Previously I tried it in the Shell but was not working. But when I used it in the code it somehow worked.
I could not find the exact reason, why it did not work before.

**Comment by wardal** [comment]
Don't see difference here, when you change manually in database or directly in code.
Maybe you just forgot to restart beat and celery workers?

**Comment by xdlgj** [comment]
> Don't see difference here, when you change manually in database or directly in code.
> Maybe you just forgot to restart beat and celery workers?

how to applay auto restart beat and celery workers?
