### ISSUE TITLE
No default appconfig defined in init.py

### ISSUE THREAD

**Issue by robvdl** [celery/django-celery-beat#81]
Because there is no default app config defined in init.py, you have to add django_celery_beat to INSTALLED_APPS like this:

django_celery_beat.apps.BeatConfig

If you don't do this and just add "django_celery_beat", it won't have a nice app label.

This can easily be resolves by setting the default app config in init.py

**Comment by robvdl** [comment]
Note: same issue exists in django_celery_results, I am raising it there too

**Comment by brianmay** [comment]
Sounds like maybe a documentation issue.

The default_app_config value is only intended for legacy use.

From https://docs.djangoproject.com/en/1.11/ref/applications/

> default_app_config allows applications that predate Django 1.7 such as django.contrib.admin to opt-in to AppConfig features without requiring users to update their INSTALLED_APPS.
>
> New applications should avoid default_app_config. Instead they should require the dotted path to the appropriate AppConfig subclass to be configured explicitly in INSTALLED_APPS.

**Comment by liquidpele** [comment]
Agreed, this should be resolved now.  Closing this. I don't see a matching one in celery-beat-results so nothing to do there.
