### ISSUE TITLE
Related model 'django_celery_beat.CrontabSchedule' cannot be resolved

### ISSUE THREAD

**Issue by pashinin** [celery/django-celery-beat#83]
Was trying to intall from git. 

1. When run `manage.py migrate` I got this:

```
Related model 'django_celery_beat.CrontabSchedule' cannot be resolved
```

2. Also when I did `makemigrations` I got:

```
Permission denied: '../site-packages/django_celery_beat/migrations/0005_auto_20170915_1139.py'
```

There is no such file actually in migrations.

```
- Alter field event on solarschedule
File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/makemigrations.py", line 232, in write_migration_files
    with io.open(writer.path, "w", encoding='utf-8') as fh:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/site-packages/django_celery_beat/migrations/0005_auto_20170915_1139.py'
```

Well, it wants to write a file, not read it. But still maybe there is unpushed migration in your files or something else?

**Comment by pashinin** [comment]
Fixed 2nd problem here: https://github.com/pashinin/django-celery-beat/commit/a87992e605fd6de026cedda74403d97f1d8ffde4

**Comment by auvipy** [comment]
https://github.com/celery/django-celery-beat/pull/84#issuecomment-345972005
