### ISSUE TITLE
Problem with pypi entry -- underscores instead of dashes

### ISSUE THREAD

**Issue by picturedots** [celery/django-celery-beat#85]
At pypi, the software is listed as "django_celery_beat" (with underscores) instead of "django-celery-beat" (with hyphens), which means that the pypi entry doesn't match what you see when you install via via ( "django-celery-beat==1.0.1" )

And curiously enough, the link in the Readme shows 

**Download:**  http://pypi.python.org/pypi/django-celery-beat
(with dashes)

but that actually redirects to 

https://pypi.python.org/pypi/django_celery_beat
(with underscores).

**Comment by wardal** [comment]
Hi @picturedots . I have this rows in my requirements.txt and it's working fine when I try to install this packages via pip install -r requirements.txt
```
celery==4.1.0
redis==2.10.6
django-celery-beat==1.0.1
django-celery-results==1.0.1
```

**Comment by picturedots** [comment]
Yes, that's correct that pip works.  But some things don't, for example django-extensions pipchecker:

`root@b0c64ee0503b:/code# manage.py pipchecker
django-celery-beat 1.0.1         release is not on pypi (check capitalization and/or --extra-index-url)
root@b0c64ee0503b:/code#`

Without really understanding the issue, I'm guessing that pip handles the automatically, but django-extensions pipchecker doesn't handle the redirect properly.

**Comment by thedrow** [comment]
This is fixed in the new version.
