### ISSUE TITLE
Schedule ad hoc job to be run immediately?

### ISSUE THREAD

**Issue by jameslao** [celery/django-celery-beat#87]
Hi, I feel it would be a very useful feature for admins if they can just kick off a job on an ad-hoc basis. Would it make sense to add this?

**Comment by brianmay** [comment]
Why not just add a user interface to your app (or admin) that runs a given celery task immediately? I think this might be outside the scope of django-celery-beat(?).

**Comment by jameslao** [comment]
That's doable but since all the tasks are already listed in celery beat, this small addition would be very handy.

**Comment by bradshjg** [comment]
that's currently implemented as a admin action for periodic tasks, what were you thinking wrt the interface?

https://github.com/celery/django-celery-beat/blob/190ae10ff46596095973138d4edf59c23c6a14f1/django_celery_beat/admin.py#L120

**Comment by jameslao** [comment]
This run task is good but it's running the task in foreground instead of background. Could we put an "immediate" option in the scheduler along with others (every hour, day, etc)?

**Comment by bradshjg** [comment]
@jameslao what do you mean by running in the foreground? AFAIK it fires of a job that gets picked up and ran by a worker.

**Comment by jameslao** [comment]
@bradshjg  Sorry I must have been misled by the prompt of "task ** has been run". I think we can close this one.
