### ISSUE TITLE
Endless migrations creation

### ISSUE THREAD

**Issue by wardal** [celery/django-celery-beat#91]
Each time when execute `python manage.py makemigrations` it will create new migration:

```
(qb_celery) python manage.py makemigrations
Migrations for 'django_celery_beat':
  /home/user/.virtualenvs/qb_celery/lib/python3.5/site-packages/django_celery_beat/migrations/0015_auto_20171101_1607.py
    - Alter field event on solarschedule
(qb_celery) python manage.py makemigrations
Migrations for 'django_celery_beat':
  /home/user/.virtualenvs/qb_celery/lib/python3.5/site-packages/django_celery_beat/migrations/0016_auto_20171101_1607.py
    - Alter field event on solarschedule
(qb_celery) python manage.py makemigrations
Migrations for 'django_celery_beat':
  /home/user/.virtualenvs/qb_celery/lib/python3.5/site-packages/django_celery_beat/migrations/0017_auto_20171101_1607.py
    - Alter field event on solarschedule
```
The reason for that:

`SOLAR_SCHEDULES = [(x, _(x)) for x in schedules.solar._all_events]`

all_events:
```
_all_events = {
        'dawn_astronomical',
        'dawn_nautical',
        'dawn_civil',
        'sunrise',
        'solar_noon',
        'sunset',
        'dusk_civil',
        'dusk_nautical',
        'dusk_astronomical',
    }
```
so each time, when we import `from celery import schedules` it gives for SOLAR_SCHEDULES dict with different order.

**Comment by raratiru** [comment]
I have reached number 0050 and still counting! 🥇

**Comment by syurchenko** [comment]
`SOLAR_SCHEDULES = [(x, _(x)) for x in sorted(schedules.solar._all_events)]` solves this problem.
Set needs to be sorted before creating choices tuple.
Fix please in next release

**Comment by wardal** [comment]
@syurchenko it was already pull requested :) Waiting for authors response to it.

**Comment by fuatu** [comment]
I still have this issue it is not fixed.

**Comment by sobolevn** [comment]
I guess that the fix is not yet released. The last release was in October https://github.com/celery/django-celery-beat/releases

**Comment by thedrow** [comment]
I will release as soon as I can. Please use master for now.
