### ISSUE TITLE
master tests failing

### ISSUE THREAD

**Issue by brianmay** [celery/django-celery-beat#97]
Please ensure tests pass on master branch.

As is tests are failing on pull requests, and I suspect this is because the master branch is broken, not because the pull requests themselves are broken.

**Comment by mbaechtold** [comment]
My attempt of solving this issue can be found in the pull request https://github.com/celery/django-celery-beat/pull/118

**Comment by mbaechtold** [comment]
@brianmay, the tests on the master branch are passing now. If this satisfy your initial request to this project, you may close this issue.
